### ISSUE TITLE
KeyError: 'parallaxy'

### ISSUE THREAD

**Issue by alderven** [pythonarcade/arcade#1001]
Run this code:

```
import arcade
arcade.load_tilemap('map.json')
```

Getting error:
```
Traceback (most recent call last):
  File "C:/parallax.py", line 2, in <module>
    arcade.load_tilemap('map.json')
  File "C:\Program Files\Python38\lib\site-packages\arcade\tilemap\tilemap.py", line 880, in load_tilemap
    return TileMap(
  File "C:\Program Files\Python38\lib\site-packages\arcade\tilemap\tilemap.py", line 161, in __init__
    self.tiled_map = pytiled_parser.parse_map(map_file)
  File "C:\Program Files\Python38\lib\site-packages\pytiled_parser\tiled_map.py", line 155, in parse_map
    layers=[layer.cast(layer_, parent_dir) for layer_ in raw_tiled_map["layers"]],
  File "C:\Program Files\Python38\lib\site-packages\pytiled_parser\tiled_map.py", line 155, in <listcomp>
    layers=[layer.cast(layer_, parent_dir) for layer_ in raw_tiled_map["layers"]],
  File "C:\Program Files\Python38\lib\site-packages\pytiled_parser\layer.py", line 495, in cast
    return _cast_tile_layer(raw_layer)
  File "C:\Program Files\Python38\lib\site-packages\pytiled_parser\layer.py", line 379, in _cast_tile_layer
    tile_layer = TileLayer(**_get_common_attributes(raw_layer).__dict__)
  File "C:\Program Files\Python38\lib\site-packages\pytiled_parser\layer.py", line 361, in _get_common_attributes
    raw_layer["parallaxx"], raw_layer["parallaxy"]
KeyError: 'parallaxy'
```

`map.json`:

```
{ "compressionlevel":-1,
 "height":2,
 "infinite":false,
 "layers":[
        {
         "data":[0, 0, 0, 0],
         "height":2,
         "id":1,
         "name":"LAYER1",
         "opacity":1,
         "parallaxx":2,
         "type":"tilelayer",
         "visible":true,
         "width":2,
         "x":0,
         "y":0
        }],
 "nextlayerid":2,
 "nextobjectid":1,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.7.2",
 "tileheight":45,
 "tilesets":[],
 "tilewidth":45,
 "type":"map",
 "version":"1.6",
 "width":2
}
```

What I do is I'm adding parallax according to this instruction: https://doc.mapeditor.org/en/stable/manual/layers/#parallax-scrolling-factor. But when I change `Parallax Factor`/`X` from `1,00` to any other value I start getting error.
![изображение](https://user-images.githubusercontent.com/21060932/136982111-2323eabb-8ceb-487a-bb9b-86c53a6c570c.png)

**Comment by pvcraven** [comment]
Ah, looks like it assumes if one if them is set, they both are. If you set y to 1.01 I would guess it will not error out?

**Comment by Cleptomania** [comment]
I can push a fix to pytiled-parser for this tonight. I think we assumed that was the case as most every other X/Y and/or Width/Height value in Tiled functions that way.

pytiled-parser issue: https://github.com/benjamin-kirkbride/pytiled_parser/issues/45

**Comment by Cleptomania** [comment]
Fixed this with v1.5.4 of pytiled-parser. Development branch of Arcade has the fix, will be in the next release.

**Comment by alderven** [comment]
> Ah, looks like it assumes if one if them is set, they both are. If you set y to 1.01 I would guess it will not error out?

that is correct

**Comment by einarf** [comment]
2.6.4 released
