### ISSUE TITLE
All docstrings currently fail to render during doc build

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1030]
### What documentation needs to change? 
All doc for the API fails to generate. @mlr07 and @nfearnley first reported this problem on discord.

### Where is it located?
Anything under the API section for 2.6.5 doc on the arcade site ([sound as an example](https://api.arcade.academy/en/2.6.5/api/sound.html)). Local doc builds for tip of development also show the same issue. [2.6.4 works fine](https://api.arcade.academy/en/2.6.4/api/sound.html).

### What is wrong with it? How can it be improved?
Restore generation for doc.

### Logs during local build
Commit c77b619b seems to work fine. I suspect this is due to changes made in 25fff4e65 as a way to fix fonts because of errors during documentation build:

```
WARNING: autodoc: failed to import function 'rand_vec_magnitude' from module 'arcade'; the following exception was raised:
Traceback (most recent call last):
  File "c:\users\user\pycharmprojects\arcade\lib\site-packages\sphinx\ext\autodoc\importer.py", line 70, in import_module
    return importlib.import_module(modname)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\user\Projects\arcade\arcade\__init__.py", line 63, in <module>
    pyglet.font.base.Font.texture_width = 4096
AttributeError: module 'pyglet.font' has no attribute 'base'

WARNING: autodoc: failed to import function 'rand_vec_spread_deg' from module 'arcade'; the following exception was raised:
Traceback (most recent call last):
  File "c:\users\user\pycharmprojects\arcade\lib\site-packages\sphinx\ext\autodoc\importer.py", line 70, in import_module
    return importlib.import_module(modname)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\user\Projects\arcade\arcade\__init__.py", line 63, in <module>
    pyglet.font.base.Font.texture_width = 4096
AttributeError: module 'pyglet.font' has no attribute 'base'

WARNING: autodoc: failed to import function 'configure_logging' from module 'arcade'; the following exception was raised:
Traceback (most recent call last):
  File "c:\users\user\pycharmprojects\arcade\lib\site-packages\sphinx\ext\autodoc\importer.py", line 70, in import_module
    return importlib.import_module(modname)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\user\Projects\arcade\arcade\__init__.py", line 63, in <module>
    pyglet.font.base.Font.texture_width = 4096
AttributeError: module 'pyglet.font' has no attribute 'base'

WARNING: autodoc: failed to import class 'NoOpenGLException' from module 'arcade'; the following exception was raised:
Traceback (most recent call last):
  File "c:\users\user\pycharmprojects\arcade\lib\site-packages\sphinx\ext\autodoc\importer.py", line 70, in import_module
    return importlib.import_module(modname)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\user\Projects\arcade\arcade\__init__.py", line 63, in <module>
    pyglet.font.base.Font.texture_width = 4096
AttributeError: module 'pyglet.font' has no attribute 'base'

WARNING: autodoc: failed to import class 'View' from module 'arcade'; the following exception was raised:
Traceback (most recent call last):
  File "c:\users\user\pycharmprojects\arcade\lib\site-packages\sphinx\ext\autodoc\importer.py", line 70, in import_module
    return importlib.import_module(modname)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\user\Projects\arcade\arcade\__init__.py", line 63, in <module>
    pyglet.font.base.Font.texture_width = 4096
AttributeError: module 'pyglet.font' has no attribute 'base'
```

**Comment by pushfoo** [comment]
@einarf do we need to bump pyglet's dev version number to fix this?

**Comment by pushfoo** [comment]
I think we might be able to fix this by conditionally excluding setting the atlas size [whenever sphinx is currently loaded or running](https://stackoverflow.com/questions/20843737/check-if-sphinx-doc-called-the-script).

**Comment by pvcraven** [comment]
I hacked a quick solution I hope doesn't cause more problems. We'll need to fix properly soon.

**Comment by pushfoo** [comment]
2.6.5 on api.arcade.academy is still broken. latest works though.

**Comment by einarf** [comment]
This was definitely fixed

**Comment by einarf** [comment]
Also, we are bulding docs on `git push` now, so this is not likely to appen again in the future.

**Comment by einarf** [comment]
2.6.6 is out and docs are working
