### ISSUE TITLE
error on "arcade.examples.shapes"

### ISSUE THREAD

**Issue by ayukoid** [pythonarcade/arcade#1045]
### Actual behavior:

```
Traceback (most recent call last):
  File "E:\programming\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\programming\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\programming\Python38-32\lib\site-packages\arcade\examples\shapes.py", line 144, in <module>
    main()
  File "E:\programming\Python38-32\lib\site-packages\arcade\examples\shapes.py", line 139, in main
    MyGame()
  File "E:\programming\Python38-32\lib\site-packages\arcade\examples\shapes.py", line 77, in __init__
    super().__init__(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)
  File "E:\programming\Python38-32\lib\site-packages\arcade\application.py", line 122, in __init__
    super().__init__(width=width, height=height, caption=title,
  File "E:\programming\Python38-32\lib\site-packages\pyglet\window\win32\__init__.py", line 130, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "E:\programming\Python38-32\lib\site-packages\pyglet\window\__init__.py", line 609, in __init__
    self._create_projection()
  File "E:\programming\Python38-32\lib\site-packages\pyglet\window\__init__.py", line 613, in _create_projection
    self.ubo = self._default_program.uniform_blocks['WindowBlock'].create_ubo()
KeyError: 'WindowBlock'
```

### Expected behavior:

The example `arcade.examples.shapes` to run

### Steps to reproduce/example code:

```
import arcade
import random

# Set up the constants
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "Shapes!"

NUMBER_OF_SHAPES = 500


class Shape:
    """ Generic base shape class """
    def __init__(self, x, y, width, height, angle, delta_x, delta_y,
                 delta_angle, color):
        self.x = x
        self.y = y
        self.width = width
        self.height = height
        self.angle = angle
        self.delta_x = delta_x
        self.delta_y = delta_y
        self.delta_angle = delta_angle
        self.color = color

    def move(self):
        self.x += self.delta_x
        self.y += self.delta_y
        self.angle += self.delta_angle
        if self.x < 0 and self.delta_x < 0:
            self.delta_x *= -1
        if self.y < 0 and self.delta_y < 0:
            self.delta_y *= -1
        if self.x > SCREEN_WIDTH and self.delta_x > 0:
            self.delta_x *= -1
        if self.y > SCREEN_HEIGHT and self.delta_y > 0:
            self.delta_y *= -1


class Ellipse(Shape):

    def draw(self):
        arcade.draw_ellipse_filled(self.x, self.y, self.width, self.height,
                                   self.color, self.angle)


class Rectangle(Shape):

    def draw(self):
        arcade.draw_rectangle_filled(self.x, self.y, self.width, self.height,
                                     self.color, self.angle)


class Line(Shape):

    def draw(self):
        arcade.draw_line(self.x, self.y,
                         self.x + self.width, self.y + self.height,
                         self.color, 2)


class MyGame(arcade.Window):
    """ Main application class. """

    def __init__(self):
        # Call the parent __init__
        super().__init__(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)

        # Create a shape list
        self.shape_list = []

        for i in range(NUMBER_OF_SHAPES):

            # Random spot
            x = random.randrange(0, SCREEN_WIDTH)
            y = random.randrange(0, SCREEN_HEIGHT)

            # Random size
            width = random.randrange(15, 40)
            height = random.randrange(15, 40)

            # Random angle
            angle = random.randrange(0, 360)

            # Random movement
            d_x = random.randrange(-3, 4)
            d_y = random.randrange(-3, 4)
            d_angle = random.randrange(-3, 4)

            # Random color
            red = random.randrange(256)
            green = random.randrange(256)
            blue = random.randrange(256)
            alpha = random.randrange(256)

            # Random line, ellipse, or rect
            shape_type = random.randrange(3)

            if shape_type == 0:
                shape = Rectangle(x, y, width, height, angle, d_x, d_y,
                                  d_angle, (red, green, blue, alpha))
            elif shape_type == 1:
                shape = Ellipse(x, y, width, height, angle, d_x, d_y,
                                d_angle, (red, green, blue, alpha))
            else:
                shape = Line(x, y, width, height, angle, d_x, d_y,
                             d_angle, (red, green, blue, alpha))

            # Add this new shape to the list
            self.shape_list.append(shape)

    def on_update(self, dt):
        """ Move everything """
        for shape in self.shape_list:
            shape.move()

    def on_draw(self):
        """ Render the screen. """

        # Clear teh screen
        arcade.start_render()

        # Draw the shapes
        for shape in self.shape_list:
            shape.draw()


def main():
    MyGame()
    arcade.run()


if __name__ == "__main__":
    main()
```

**Comment by pvcraven** [comment]
The program runs for me without error, so I'm not able to replicate it yet.

Please make sure Arcade and Pyglet are the correct versions. Arcade should be 2.6.6, and pyglet should be 2.0dev11.

**Comment by Cleptomania** [comment]
As Paul said the most likely candidate is an outdated version of Pyglet.

Do other examples run? This appears to be an issue with setting the projection of the window from Pyglet and that would happen on every example.

**Comment by einarf** [comment]
Definitely share arcade and pyglet version installed including what hardware you are running this on. 

What seems to happen here is that pyglet is creating a default shader and it doesn't have the expected `WindowBlock` uniform. That suggests there something weird happening when the shader is compiled.

**Comment by ayukoid** [comment]
pyglet version is `2.0.dev11`
```
>_ pip show pyglet
Name: pyglet
Version: 2.0.dev11
Summary: Cross-platform windowing and multimedia library
Home-page: http://pyglet.readthedocs.org/en/latest/
Author: Alex Holkner
Author-email: Alex.Holkner@gmail.com
License: BSD
Location: e:\programming\python38-32\lib\site-packages
Requires:
Required-by: arcade
```
arcade too is `2.6.6`

And, no. None of the examples work.. and the same error is made..

<hr>

My hardware:
OS: Windows 7 :)
Arch: x86
Processor: Intel i3 M330 @ 2.13GHz, 2133 Mhz, 2 Cores, 4 Logical Precessors
Graphics: Intel HD Graphics (Core i3) 8.15.10.2993
**anything else? & FYI: The laptop is ~10 years old

**Comment by Cleptomania** [comment]
Ahh I believe that only supports up to OpenGL 2.1 from what I can find. Arcade needs at least OpenGL 3.3

**Comment by einarf** [comment]
Yeah that looks like a HW support or driver issue. I also don't think pyglet has any windows 7 support any more.

**Comment by ayukoid** [comment]
Oh no!
This means without a driver update to the hardware that manufacturer stopped supporting, I can't run arcade?
Then it's probably impossible!

**Comment by ayukoid** [comment]
I really appreciate the support that you provided
Shall I close this issue now?

**Comment by einarf** [comment]
> I really appreciate the support that you provided Shall I close this issue now?

I think so. Your CPU is from Q1 2010, so the driver support probably stopped more than 5 years ago. You might have better luck on linux actually. That is the only hope, but it might be that your integrated graphics don't even have the intructions needed.

Will close this for now. Be free to re-open if needed.
