### ISSUE TITLE
Can't open new window after closing previous

### ISSUE THREAD

**Issue by indeed999** [pythonarcade/arcade#1074]
Trying to open a window after the first one is closed by the user, but get this error:
```python
Traceback (most recent call last):
  File "D:\Python\PFlows\empty.py", line 101, in <module>
    main()
  File "D:\Python\PFlows\empty.py", line 94, in main
    game = MyGame(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)
  File "D:\Python\PFlows\empty.py", line 27, in __init__
    super().__init__(width, height, title)
  File "D:\Python\PFlows\venv\lib\site-packages\arcade\application.py", line 125, in __init__
    super().__init__(width=width, height=height, caption=title,
  File "D:\Python\PFlows\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 138, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "D:\Python\PFlows\venv\lib\site-packages\pyglet\window\__init__.py", line 608, in __init__
    self.set_visible(True)
  File "D:\Python\PFlows\venv\lib\site-packages\arcade\application.py", line 483, in set_visible
    super().set_visible(visible)
  File "D:\Python\PFlows\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 437, in set_visible
    self.dispatch_event('on_resize', self._width, self._height)
  File "D:\Python\PFlows\venv\lib\site-packages\pyglet\window\__init__.py", line 1327, in dispatch_event
    super().dispatch_event(*args)
  File "D:\Python\PFlows\venv\lib\site-packages\pyglet\event.py", line 422, in dispatch_event
    if getattr(self, event_type)(*args):
  File "D:\Python\PFlows\venv\lib\site-packages\arcade\application.py", line 418, in on_resize
    self.set_viewport(original_viewport[0],
  File "D:\Python\PFlows\venv\lib\site-packages\arcade\application.py", line 498, in set_viewport
    set_viewport(left, right, bottom, top)
  File "D:\Python\PFlows\venv\lib\site-packages\arcade\window_commands.py", line 182, in set_viewport
    window.ctx.projection_2d = left, right, bottom, top
  File "D:\Python\PFlows\venv\lib\site-packages\arcade\context.py", line 242, in projection_2d
    self._projection_2d_buffer.write(self._projection_2d_matrix)
  File "D:\Python\PFlows\venv\lib\site-packages\arcade\gl\buffer.py", line 164, in write
    gl.glBufferSubData(gl.GL_ARRAY_BUFFER, gl.GLintptr(offset), size, data)
  File "D:\Python\PFlows\venv\lib\site-packages\pyglet\gl\lib.py", line 114, in errcheck
    raise GLException('(0x%x): %s' % (error, msg))
pyglet.gl.lib.GLException: (0x501): Invalid value. A numeric argument is out of range.

Process finished with exit code 1

```

Example code (https://api.arcade.academy/en/latest/examples/starting_template.html#starting-template) just with again calling main():

```python
import arcade

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "Starting Template"

class MyGame(arcade.Window):     
    def __init__(self, width, height, title):
        super().__init__(width, height, title)
        arcade.set_background_color(arcade.color.AMAZON)
      
    def setup(self):
          pass

    def on_draw(self):
        self.clear()

    def on_update(self, delta_time):        
        pass

    def on_key_press(self, key, key_modifiers):       
        pass

    def on_key_release(self, key, key_modifiers):       
        pass

    def on_mouse_motion(self, x, y, delta_x, delta_y):       
        pass

    def on_mouse_press(self, x, y, button, key_modifiers):       
        pass

    def on_mouse_release(self, x, y, button, key_modifiers):      
        pass

def main():    
    game = MyGame(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)
    game.setup()
    arcade.run()

if __name__ == "__main__":
    main()
    main()
```

Adding `arcade.exit()` to `main()` after `arcade.run()` also doesn't help, the same error

If it is normal behavior, how it is possible to rerun the same window after it was closed by the user?

**Comment by einarf** [comment]
If there is anything you can do to avoid closing the window, that is much simpler. I think pyglet have some hide/minimize functions.

**Comment by indeed999** [comment]
@einarf  Ok, thanks! How it is possible to handle the event "clicking on the windows close button" to change it to pyglet hide/minimize?

**Comment by einarf** [comment]
Can you explain how your application works so I can understand better why a window needs to be opened and closed? It helps figuring out what needs to be fixed here.

**Comment by indeed999** [comment]
@einarf 
1. I use PySimpleGui for the interface where the user can insert some properties
2. After clicking on the button PySimpleGui window is hiding and creating an Arcade window
3. User do smth in Arcade windows and close it after
4. PySimpleGui is unhiding, and the user can change some properties
5. User can again run the same Arcade window with other properties or other new Arcade window (all handlers, setup() and on_update(), on_draw() methods are different)
6. User can repeat changing properties and rerunning Arcade windows as many as wants

**Comment by einarf** [comment]
Fixed in development branch. Can you try this version?

**Comment by indeed999** [comment]
@einarf  Works perfectly! Big thanks!

**Comment by einarf** [comment]
2.6.11 released
