### ISSUE TITLE
arcade.examples.gui_slider gives an error upon execution

### ISSUE THREAD

**Issue by andrewhong04** [pythonarcade/arcade#1228]
## Bug Report
`arcade.examples.gui_slider` gives an error upon execution

## System Info
```
Arcade 2.6.14
-------------
vendor: NVIDIA Corporation
renderer: GeForce RTX 2070/PCIe/SSE2
version: (4, 6)
python: 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
platform: win32
```

### Actual behavior:
```
PS C:\Users\novia> python -m arcade.examples.gui_slider
Exception ignored on calling ctypes callback function: <function _enum_font_names at 0x000002634411E1F0>
Traceback (most recent call last):
  File "C:\Users\novia\AppData\Local\Programs\Python\Python39\lib\site-packages\pyglet\font\win32query.py", line 343, in _enum_font_names
    name = lf.lfFaceName.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte
Exception ignored on calling ctypes callback function: <function _enum_font_names at 0x000002634411E1F0>
Traceback (most recent call last):
  File "C:\Users\novia\AppData\Local\Programs\Python\Python39\lib\site-packages\pyglet\font\win32query.py", line 343, in _enum_font_names
    name = lf.lfFaceName.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte
Exception ignored on calling ctypes callback function: <function _enum_font_names at 0x000002634411E1F0>
Traceback (most recent call last):
  File "C:\Users\novia\AppData\Local\Programs\Python\Python39\lib\site-packages\pyglet\font\win32query.py", line 343, in _enum_font_names
    name = lf.lfFaceName.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte
Exception ignored on calling ctypes callback function: <function _enum_font_names at 0x000002634411E1F0>
Traceback (most recent call last):
  File "C:\Users\novia\AppData\Local\Programs\Python\Python39\lib\site-packages\pyglet\font\win32query.py", line 343, in _enum_font_names
    name = lf.lfFaceName.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte
```

### Expected behavior:
No errors at all.

### Steps to reproduce/example code:
Run `python -m arcade.examples.gui_slider`

**Comment by pushfoo** [comment]
How did you install arcade? Via pip or git?

I can't replicate this under Linux with my setup:
```
Arcade 2.6.14
-------------
vendor: Intel
renderer: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
version: (4, 6)
python: 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
platform: linux
```

**Comment by andrewhong04** [comment]
> How did you install arcade? Via pip or git?
> 
> I can't replicate this under Linux with my setup:
> 
> ```
> Arcade 2.6.14
> -------------
> vendor: Intel
> renderer: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
> version: (4, 6)
> python: 3.9.2 (default, Feb 28 2021, 17:03:44) 
> [GCC 10.2.1 20210110]
> platform: linux
> ```

I installed via pip.

**Comment by pushfoo** [comment]
What happens when you run a version with the text label removed? _EDIT: fixed to use 2.6.14 style_
```py
import arcade
from arcade.experimental.uislider import UISlider
from arcade.gui import UIManager, UIAnchorWidget, UILabel
from arcade.gui.events import UIOnChangeEvent


class UIMockup(arcade.Window):
    def __init__(self):
        super().__init__(800, 600, "UI Mockup", resizable=True)
        self.manager = UIManager()
        self.manager.enable()
        arcade.set_background_color(arcade.color.DARK_BLUE_GRAY)

        ui_slider = UISlider(value=50, width=300, height=50)

        self.manager.add(UIAnchorWidget(child=ui_slider))

    def on_draw(self):
        self.clear()
        self.manager.draw()


if __name__ == '__main__':
    window = UIMockup()
    arcade.run()
```

**Comment by pushfoo** [comment]
Also, the output you posted starts with this line:
```
Exception ignored on calling ctypes callback function: <function _enum_font_names at 0x000002634411E1F0>
```
Does the demo still run despite outputting the error, or is it crashing?

**Comment by pushfoo** [comment]
Based on discord discussion, we've narrowed this down to an issue involving pyglet and Win32 rather than arcade itself: https://github.com/pyglet/pyglet/issues/622

**Comment by andrewhong04** [comment]
@pushfoo and I have resolved the issue.
