### ISSUE TITLE
Headless mode seems to still require a display

### ISSUE THREAD

**Issue by shadow7412** [pythonarcade/arcade#1430]
## Bug Report

I have unit tests running in gitlab pipelines, inside a docker image.

## System Info

Run this and paste the output here: python -m arcade

I can't actually run this inside the docker container, as it exhibits the same behaviour. Here is the stack trace;

```
root@2909edaf0cad:/tm# python -m arcade
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/site-packages/arcade/__main__.py", line 6, in <module>
    window = arcade.Window()
  File "/usr/local/lib/python3.10/site-packages/arcade/application.py", line 116, in __init__
    display = pyglet.canvas.get_display()
  File "/usr/local/lib/python3.10/site-packages/pyglet/canvas/__init__.py", line 94, in get_display
    return Display()
  File "/usr/local/lib/python3.10/site-packages/pyglet/canvas/xlib.py", line 123, in __init__
    raise NoSuchDisplayException('Cannot connect to "%s"' % name)
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"
```

I'm using the image `shadowbert/python:3.10-with-freeglut3-dev` and the following is my requirements file. These two should allow people to spin up the exact same environment.

```
arcade==2.6.16
black==22.10.0
names==0.3.0
pre-commit==2.20.0
pyinstaller==5.6.2
pylint==2.15.5
pylint-print==1.0.0
pytest==7.2.0
pytest-cov==4.0.0
```

### Actual behavior:

```
______________________ ERROR at setup of test_create_unit ______________________
    @pytest.fixture(scope="session", autouse=True)
    def arcade_window():
>       window = arcade.open_window(100, 100)
tests/conftest.py:10: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.10/site-packages/arcade/application.py:791: in open_window
    _window = Window(width, height, window_title, resizable=resizable, update_rate=None,
/usr/local/lib/python3.10/site-packages/arcade/application.py:116: in __init__
    display = pyglet.canvas.get_display()
/usr/local/lib/python3.10/site-packages/pyglet/canvas/__init__.py:94: in get_display
    return Display()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <pyglet.canvas.xlib.XlibDisplay object at 0x153d44e82b00>, name = None
x_screen = 0
    def __init__(self, name=None, x_screen=None):
        if x_screen is None:
            x_screen = 0
    
        if isinstance(name, str):
            name = c_char_p(name.encode('ascii'))
    
        self._display = xlib.XOpenDisplay(name)
        if not self._display:
>           raise NoSuchDisplayException('Cannot connect to "%s"' % name)
E           pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"
/usr/local/lib/python3.10/site-packages/pyglet/canvas/xlib.py:123: NoSuchDisplayException
```

### Expected behavior:

Window should be successfully created with no expectation of there being a display (in headless mode, anyway)

### Steps to reproduce/example code:

Apparently, just starting a docker environment with the above image and running `python -m arcade` is enough to reproduce the issue.

**Comment by Cleptomania** [comment]
Have you set the `ARCADE_HEADLESS` environment variable to `True`? This seems to be attempting to creating a display with xlib, we use egl for headless operation.

**Comment by shadow7412** [comment]
I just tried it again - looks like it's entirely possible that the way I was setting that variable didn't work (perhaps it didn't get set in time or something).

I'll just make some changes to the pipeline and verify it all works before closing this ticket.

**Comment by shadow7412** [comment]
Yep, the environment variable was being set too late.

Sigh.

Thanks for your help.
