### ISSUE TITLE
label crashes when applying style to rgba, and also when initialized with rgb with ValueError

### ISSUE THREAD

**Issue by csd4ni3l** [pythonarcade/arcade#1469]
So using pyglet labels seems like it broke styling, because if you initalize a a button with rgb, it crashes, if you initalize it with rgba it doesnt, but after you apply style and it realized that its rgba it crashes.
error message:
```
File "/home/csdaniel/.local/lib/python3.8/site-packages/pyglet/text/document.py", line 596, in set_style
    return super().set_style(0, len(self.text), attributes)
  File "/home/csdaniel/.local/lib/python3.8/site-packages/pyglet/text/document.py", line 505, in set_style
    self.dispatch_event('on_style_text', start, end, attributes)
  File "/home/csdaniel/.local/lib/python3.8/site-packages/pyglet/event.py", line 415, in dispatch_event
    if handler(*args):
  File "/home/csdaniel/.local/lib/python3.8/site-packages/pyglet/text/layout.py", line 1495, in on_style_text
    self._update_color()
  File "/home/csdaniel/.local/lib/python3.8/site-packages/pyglet/text/layout.py", line 1397, in _update_color
    _vertex_list.colors = colors[start:start + len(_vertex_list.colors)]
  File "/home/csdaniel/.local/lib/python3.8/site-packages/pyglet/graphics/vertexdomain.py", line 354, in __setattr__
    getattr(self, name)[:] = value
ValueError: Can only assign sequence of same size
```

How to reproduce:

1. create a uiflatbuton object
2. modify style with button.style
3. crash on next frame

Example of reproduction:
```py
button = arcade.gui.UIFlatButton(text='test',x=window.width/2,y=window.height/2)
manager.add(button)
button.style['normal']['font_color'] = (0,0,0,255)
```

**Comment by eruvanos** [comment]
No crash running with the latest dev version from Github:

```
import arcade
from arcade import Window
from arcade.gui import UIManager


class MyWindow(Window):

    def __init__(self):
        super().__init__()

        self.manager = UIManager()
        self.manager.enable()

        self.button = arcade.gui.UIFlatButton(text='test', style={
            'normal': {'bg': (0, 150, 0, 255), 'font_color': (30, 30, 30)},
            'hover': {'bg': (16, 179, 35, 255), 'font_color': (30, 30, 30, 255)},
            'press': {'bg': (0, 150, 0, 255), 'font_color': (30, 30, 30, 255)},
            'disabled': {'bg': (0, 150, 0), 'font_color': (30, 30, 30, 255)}})
        self.button.style['normal']['font_color'] = (0, 0, 0)
        self.button.center_on_screen()
        self.manager.add(self.button)

    def on_draw(self):
        arcade.start_render()
        self.manager.draw()

    def on_key_press(self, symbol: int, modifiers: int):
        print("modify")
        self.button.style['normal']['font_color'] = (0, 0, 0, 255)
        self.button.text = "Clicked"


if __name__ == '__main__':
    MyWindow().run()

```

@csd4ni3l Could you check if there is something missing in the example?

**Comment by csd4ni3l** [comment]
i think the missing thing is that the uiflatbutton needs to have the style argument when you create the button. If you have rgb font color in that style it crashes instantly, if you have rgba, then when you modify the style it crashes

**Comment by eruvanos** [comment]
Updated the example, still no crash :/

**Comment by csd4ni3l** [comment]
i meant not modifying the button.style object when creating it, but using the style argument of the button

**Comment by csd4ni3l** [comment]
i will be able to put out my style dict and how i initialize everything in like 7.5 hours sorry

**Comment by csd4ni3l** [comment]
my style dict:
{'normal': {'bg': (0,150,0,255), 'font_color': (30, 30, 30, 255)}, 'hover': {'bg': (16, 179, 35,255), 'font_color': (30, 30, 30, 255)}, 'press': {'bg': (0,150,0,255), 'font_color': (30, 30, 30, 255)}, 'disabled': {'bg': (0,150,0), 'font_color': (30, 30, 30, 255)}}
just use style=button_style in the button arguments,if you use an rgb font color it will crash

**Comment by eruvanos** [comment]
I updated the example, could you check if it crashes on your machine? because it does not on my :/

**Comment by csd4ni3l** [comment]
yes it does crash:
Traceback (most recent call last):
  File "/home/csdaniel/Dokumentumok/python3/Endless-Zombie-Shooter/code/test2.py", line 70, in <module>
    MyWindow().run()
  File "/home/csdaniel/.local/lib/python3.8/site-packages/arcade/application.py", line 269, in run
    arcade.run()
  File "/home/csdaniel/.local/lib/python3.8/site-packages/arcade/window_commands.py", line 292, in run
    pyglet.app.run(window._draw_rate)
  File "/home/csdaniel/.local/lib/python3.8/site-packages/pyglet/app/__init__.py", line 107, in run
    event_loop.run(interval)
  File "/home/csdaniel/.local/lib/python3.8/site-packages/pyglet/app/base.py", line 186, in run
    timeout = self.idle()
  File "/home/csdaniel/.local/lib/python3.8/site-packages/pyglet/app/base.py", line 247, in idle
    self.clock.call_scheduled_functions(dt)
  File "/home/csdaniel/.local/lib/python3.8/site-packages/pyglet/clock.py", line 262, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "/home/csdaniel/.local/lib/python3.8/site-packages/pyglet/app/base.py", line 153, in _redraw_windows
    window.dispatch_event('on_draw')
  File "/home/csdaniel/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 1363, in dispatch_event
    super().dispatch_event(*args)
  File "/home/csdaniel/.local/lib/python3.8/site-packages/pyglet/event.py", line 422, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/home/csdaniel/Dokumentumok/python3/Endless-Zombie-Shooter/code/test2.py", line 61, in on_draw
    self.manager.draw()
  File "/home/csdaniel/.local/lib/python3.8/site-packages/arcade/gui/ui_manager.py", line 270, in draw
    self._do_render()
  File "/home/csdaniel/.local/lib/python3.8/site-packages/arcade/gui/ui_manager.py", line 192, in _do_render
    child._do_render(surface, force)
  File "/home/csdaniel/.local/lib/python3.8/site-packages/arcade/gui/widgets/__init__.py", line 370, in _do_render
    self.do_render(surface)
  File "/home/csdaniel/.local/lib/python3.8/site-packages/arcade/gui/widgets/buttons.py", line 278, in do_render
    self.apply_style(style)
  File "/home/csdaniel/.local/lib/python3.8/site-packages/arcade/gui/widgets/buttons.py", line 308, in apply_style
    self._label.layout.color = font_color
  File "/home/csdaniel/.local/lib/python3.8/site-packages/pyglet/text/__init__.py", line 309, in color
    self.document.set_style(0, len(self.document.text), {'color': color})
  File "/home/csdaniel/.local/lib/python3.8/site-packages/pyglet/text/document.py", line 596, in set_style
    return super().set_style(0, len(self.text), attributes)
  File "/home/csdaniel/.local/lib/python3.8/site-packages/pyglet/text/document.py", line 505, in set_style
    self.dispatch_event('on_style_text', start, end, attributes)
  File "/home/csdaniel/.local/lib/python3.8/site-packages/pyglet/event.py", line 415, in dispatch_event
    if handler(*args):
  File "/home/csdaniel/.local/lib/python3.8/site-packages/pyglet/text/layout.py", line 1495, in on_style_text
    self._update_color()
  File "/home/csdaniel/.local/lib/python3.8/site-packages/pyglet/text/layout.py", line 1397, in _update_color
    _vertex_list.colors = colors[start:start + len(_vertex_list.colors)]
  File "/home/csdaniel/.local/lib/python3.8/site-packages/pyglet/graphics/vertexdomain.py", line 354, in __setattr__
    getattr(self, name)[:] = value
ValueError: Can only assign sequence of same size

**Comment by csd4ni3l** [comment]
python3 -m arcade output

Arcade 2.7.1.dev12
------------------
vendor: Intel
renderer: Mesa Intel(R) UHD Graphics (ICL GT1)
version: (4, 6)
python: 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0]
platform: linux

**Comment by csd4ni3l** [comment]
maybe wrong pyglet version?

**Comment by csd4ni3l** [comment]
pyglet version: 2.0.2.1

**Comment by eruvanos** [comment]
Finally fails on my machine, thanks

**Comment by csd4ni3l** [comment]
just a small change, get_four_byte_color on the color values, btw how did you make it fail(crash)?

**Comment by einarf** [comment]
When installing dev branch now you should get pyglet 2.0.3

Also it really helps to make a runnable example triggering the bug. Saves everyone so much time 😄

**Comment by eruvanos** [comment]
I was on some branch for UIGridLayout -.-

**Comment by eruvanos** [comment]
Now I also see, that the text looks really blured

**Comment by csd4ni3l** [comment]
yeah view my message on discord, i have an example image too
