### ISSUE TITLE
'tuple' object has no attribute 'x'

### ISSUE THREAD

**Issue by alderven** [pythonarcade/arcade#1479]
## Steps to reproduce
Run code from the following example:
https://api.arcade.academy/en/latest/examples/sprite_move_scrolling_shake.html

Getting error:
```
"C:\Program Files\Python310\python.exe" D:\PROGRAMMING\temp\arcade_sprite_move_scrolling_shake\arcade_sprite_move_scrolling_shake.py 
Traceback (most recent call last):
  File "D:\PROGRAMMING\temp\arcade_sprite_move_scrolling_shake\arcade_sprite_move_scrolling_shake.py", line 224, in <module>
    main()
  File "D:\PROGRAMMING\temp\arcade_sprite_move_scrolling_shake\arcade_sprite_move_scrolling_shake.py", line 220, in main
    arcade.run()
  File "C:\Program Files\Python310\lib\site-packages\arcade\window_commands.py", line 323, in run
    pyglet.app.run()
  File "C:\Program Files\Python310\lib\site-packages\pyglet\app\__init__.py", line 107, in run
    event_loop.run(interval)
  File "C:\Program Files\Python310\lib\site-packages\pyglet\app\base.py", line 186, in run
    timeout = self.idle()
  File "C:\Program Files\Python310\lib\site-packages\pyglet\app\base.py", line 247, in idle
    self.clock.call_scheduled_functions(dt)
  File "C:\Program Files\Python310\lib\site-packages\pyglet\clock.py", line 262, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "C:\Program Files\Python310\lib\site-packages\arcade\application.py", line 318, in _dispatch_updates
    self.dispatch_event('on_update', delta_time)
  File "C:\Program Files\Python310\lib\site-packages\pyglet\window\__init__.py", line 1363, in dispatch_event
    super().dispatch_event(*args)
  File "C:\Program Files\Python310\lib\site-packages\pyglet\event.py", line 427, in dispatch_event
    raise e
  File "C:\Program Files\Python310\lib\site-packages\pyglet\event.py", line 422, in dispatch_event
    if getattr(self, event_type)(*args):
  File "D:\PROGRAMMING\temp\arcade_sprite_move_scrolling_shake\arcade_sprite_move_scrolling_shake.py", line 185, in on_update
    self.camera_sprites.shake(shake_vector,
  File "C:\Program Files\Python310\lib\site-packages\arcade\camera.py", line 152, in shake
    self.shake_velocity += velocity
  File "C:\Program Files\Python310\lib\site-packages\pyglet\math.py", line 106, in __add__
    return Vec2(self.x + other.x, self.y + other.y)
AttributeError: 'tuple' object has no attribute 'x'
```

## System Info
OS: Win 11
Python: 3.10
Arcade: 2.6.17

**Comment by einarf** [comment]
That looks like a mismatching pyglet version. you should have `2.0.dev23` installed. Optionally just grab the latest 2.7 version.

**Comment by alderven** [comment]
> That looks like a mismatching pyglet version. you should have `2.0.dev23` installed. Optionally just grab the latest 2.7 version.

I do have pyglet `2.0.3` installed. Didn't help.

**Comment by einarf** [comment]
Well. If you are using 2.6.17 the package requirements states only pyglet 2.0.dev23 works. If you do a `pip install -I arcade==2.6.17` it should downgrade your pyglet version.

If you want to use pylget 2.0.3 you need to use the latest development branch.

You should have seen a lot of stern warnings from pip about the mismatching pyglet version.

**Comment by alderven** [comment]
I've downgraded `pyglet` and Arcade window is running now but when the player touches the bombs, same error appears:

`AttributeError: 'tuple' object has no attribute 'x'`

**Comment by einarf** [comment]
Are you absolutely sure you have the right pyglet version? What did `pip list` show? This should not happen unless you ingore some stern warnings during arcade install.

**Comment by alderven** [comment]
> Are you absolutely sure you have the right pyglet version? What did `pip list` show? This should not happen unless you ingore some stern warnings during arcade install.

`pip list` shows me following:
```
Package                   Version
------------------------- -----------
arcade                    2.6.17
pyglet                    2.0.dev23
```
Can you check on your side that colliding with bomb does not throw you this error?

**Comment by pvcraven** [comment]
The example code is outdated. It needs [these changes](https://github.com/pythonarcade/arcade/commit/e5f842cbad58184cea15d662fee298826d5f786c#diff-f0f18a43462e9853142e513de289c9cff26ed8fd5d8c0ab08f7f9090bc116f30). Thanks for the report, we'll work at getting that updated.
