### ISSUE TITLE
`PymunkPhysicsEngine` throws an error when removing a sprite from `remove_from_sprite_lists` method

### ISSUE THREAD

**Issue by Ibrahim2750mi** [pythonarcade/arcade#1656]
## Bug Report

Arcade throws a key error when using `remove_from_sprites_lists` with `PymunkPhysicsEngine`.

## System Info

Arcade 3.0.0.dev20
------------------
vendor: nouveau
renderer: NV106
version: (4, 3)
python: 3.9.14 (main, Sep  7 2022, 23:43:29) 
[GCC 9.4.0]
platform: linux
pyglet version: 2.0.3
PIL version: 9.0.1

### Actual behavior:

```shell
$ python bug.py 
Traceback (most recent call last):
  File "/home/ibrahim/PycharmProjects/arcade/arcade_help/bug.py", line 55, in <module>
    main()
  File "/home/ibrahim/PycharmProjects/arcade/arcade_help/bug.py", line 51, in main
    game.run()
  File "/home/ibrahim/PycharmProjects/arcade/arcade/arcade/application.py", line 270, in run
    arcade.run()
  File "/home/ibrahim/PycharmProjects/arcade/arcade/arcade/window_commands.py", line 204, in run
    pyglet.app.run(window._draw_rate)
  File "/home/ibrahim/PycharmProjects/arcade/arcade_dev/lib/python3.10/site-packages/pyglet/app/__init__.py", line 72, in run
    event_loop.run(interval)
  File "/home/ibrahim/PycharmProjects/arcade/arcade_dev/lib/python3.10/site-packages/pyglet/app/base.py", line 151, in run
    timeout = self.idle()
  File "/home/ibrahim/PycharmProjects/arcade/arcade_dev/lib/python3.10/site-packages/pyglet/app/base.py", line 212, in idle
    self.clock.call_scheduled_functions(dt)
  File "/home/ibrahim/PycharmProjects/arcade/arcade_dev/lib/python3.10/site-packages/pyglet/clock.py", line 227, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "/home/ibrahim/PycharmProjects/arcade/arcade/arcade/application.py", line 325, in _dispatch_updates
    self.dispatch_event('on_update', delta_time)
  File "/home/ibrahim/PycharmProjects/arcade/arcade_dev/lib/python3.10/site-packages/pyglet/window/__init__.py", line 668, in dispatch_event
    super().dispatch_event(*args)
  File "/home/ibrahim/PycharmProjects/arcade/arcade_dev/lib/python3.10/site-packages/pyglet/event.py", line 387, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/home/ibrahim/PycharmProjects/arcade/arcade_help/bug.py", line 47, in on_update
    self.player_sprite.remove_from_sprite_lists()
  File "/home/ibrahim/PycharmProjects/arcade/arcade/arcade/sprite/sprite.py", line 388, in remove_from_sprite_lists
    engine.remove_sprite(self)
  File "/home/ibrahim/PycharmProjects/arcade/arcade/arcade/pymunk_physics_engine.py", line 227, in remove_sprite
    physics_object = self.sprites[sprite]
KeyError: <arcade.sprite.sprite.Sprite object at 0x7fcd7f646890>
```

### Expected behavior:

No error to be thrown and instead the sprite to be removed from the sprite list and the physics engine.

### Steps to reproduce/example code:

```python

import arcade


SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

class Game(arcade.Window):
    def __init__(self):
        super().__init__(SCREEN_WIDTH, SCREEN_HEIGHT, title='Game')
        arcade.set_background_color(arcade.color.EERIE_BLACK)

        self.total_time = 0
        self.removed = False

        self.physics_engine = arcade.PymunkPhysicsEngine(gravity=(0.0, -100.0), damping=1)

        mass = 2.0
        self.player_sprite = arcade.Sprite(
        	":resources:images/tiles/boxCrate_double.png",
        	scale=32/128,
        	center_x=400,
        	center_y=300,
        )
        self.physics_engine.add_sprite(
            self.player_sprite,
            mass=mass,
            moment_of_inertia=arcade.PymunkPhysicsEngine.MOMENT_INF,
            collision_type="player",
            friction=1,
            damping=0.4,
        )

        self.player_sprite_list = arcade.SpriteList()
        self.player_sprite_list.append(self.player_sprite)

    def on_draw(self):
        self.clear()

        # self.camera.use()
        self.player_sprite_list.draw()

    def on_update(self, delta_time: float):
        self.physics_engine.step(1 / 60.0)
        self.total_time += delta_time
        if self.total_time > 3.0 and not self.removed:
        	self.removed = True
        	self.player_sprite.remove_from_sprite_lists()

def main():
    game = Game()
    game.run()


if __name__ == '__main__':
    main()
```

**Comment by Ibrahim2750mi** [comment]
## Fix

The physics engine seems to be added twice. This line was added in #1641. I assume this is a mistake right @Cleptomania?
https://github.com/pythonarcade/arcade/blob/development/arcade/sprite/sprite.py#L406

If yes, I can make a quick pr fixing it.
