### ISSUE TITLE
MacOS M1: AttributeError: `ObjCInstance b'__NSSingleObjectArrayI' has no attribute b'type'`

### ISSUE THREAD

**Issue by domenukk** [pythonarcade/arcade#1902]
## System Info

Run this and paste the output here: python -m arcade
```bash
2023-09-16 09:44:47.295 Python[4173:2094863] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/lk/yjt48_fj7qz48cjbw214x10c00yf_x/T/org.python.python.savedState

Arcade 2.6.17
-------------
vendor: Apple
renderer: Apple M1 Pro
version: (4, 1)
python: 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)]
platform: darwin
```

### Actual behavior:

Sometimes during play (I think when jumping up), the engine crashes with the following stacktrace:

```python
Traceback (most recent call last):
  File "/<path>/client.py", line 46, in <module>
    main()
  File "/<path>/client.py", line 42, in main
    window.run()
  File "/<path>/arcade_venv/lib/python3.11/site-packages/arcade/application.py", line 257, in run
    arcade.run()
  File "/<path>/arcade_venv/lib/python3.11/site-packages/arcade/window_commands.py", line 289, in run
    pyglet.app.run()
  File "/<path>/arcade_venv/lib/python3.11/site-packages/pyglet/app/__init__.py", line 107, in run
    event_loop.run(interval)
  File "/<path>/arcade_venv/lib/python3.11/site-packages/pyglet/app/base.py", line 185, in run
    platform_event_loop.step(timeout)
  File "/<path>/arcade_venv/lib/python3.11/site-packages/pyglet/app/cocoa.py", line 147, in step
    event_type = event.type()
                 ^^^^^^^^^^
  File "/<path>/arcade_venv/lib/python3.11/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1009, in __getattr__
    raise AttributeError('ObjCInstance %s has no attribute %s' % (self.objc_class.name, name))
AttributeError: ObjCInstance b'__NSSingleObjectArrayI' has no attribute b'type'
```

### Expected behavior:

On other systems it does not crash.

### Steps to reproduce/example code:

I'm not sure when and how this occurs, sadly, it happens rarely (but often enough for me to open this bug)

**Comment by einarf** [comment]
This is a pyglet issue and was solved in later pyglet versions. We are using latest pyglet in arcade 3.0 pre-release.

**Comment by domenukk** [comment]
Thanks!
