### ISSUE TITLE
Shapely load dll error

### ISSUE THREAD

**Issue by PoriruaU3A** [pythonarcade/arcade#1908]
## System Info  Windows 10 Home, 64-bit OS

Run this and paste the output here: python -m arcade

Arcade 2.6.17
-------------
vendor: ATI Technologies Inc.
renderer: AMD Radeon(TM) R3 Graphics
version: (4, 5)
python: 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
platform: win32

### Actual behavior:

Start-up fails

### Expected behavior:

No errors

### Steps to reproduce/example code:

On Windows 10, I have a test python file containing only one line saying "import arcade". It compiles under python 3.8

I have run:
pyinstaller --noconfirm --onedir --console "C:/Playpen/Software/soxviewer/test.py"

Running the created executable I get a library load issue.
(Latest issues of arcade and PyInstaller)

C:\Playpen\Software\soxviewer\dist\test>test.exe
Traceback (most recent call last):
  File "test.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "arcade\__init__.py", line 241, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "arcade\geometry.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "arcade\geometry_shapely.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "shapely\speedups\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "shapely\geometry\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "shapely\geometry\base.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "shapely\coords.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "shapely\geos.py", line 160, in <module>
  File "shapely\geos.py", line 60, in load_dll
OSError: Could not find lib geos_c.dll or load any of its variants [].
[23524] Failed to execute script 'test' due to unhandled exception!

**Comment by cspotcode** [comment]
Shapely has been removed from arcade so the new v3.x.x does not use it.

In the meantime, uninstalling shapely should help, since arcade 2.6.17 does not actually *require* shapely.  It only attempts to load it if it's installed.

**Comment by PoriruaU3A** [comment]
Thanks cspotcode, I uninstalled shapely and rebuilt with PyInstaller. Running the executable immediately brought up an error about missing shapely code so I reinstalled shapely. I noticed that the shapely code had changed so I again rebuilt with PyInstaller and reran the executable.  Success !

**Comment by PoriruaU3A** [comment]
Latest version of shapely solves issue.
