### ISSUE TITLE
NoOpenGLException on Fedora 31

### ISSUE THREAD

**Issue by lamartire** [pythonarcade/arcade#635]
### Actual behavior:

Trying to run example code and have this exception. Also, I have installed OpenGL:

`OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.2.8`

So, I also have all required libraries (`zlib-devel`, `libjpeg`)

**Comment by einarf** [comment]
What is the exact error message / stack trace?

**Comment by lamartire** [comment]
```
Traceback (most recent call last):
  File "/home/lamartire/.local/share/virtualenvs/o5_25-5__1sqhq/lib/python3.7/site-packages/arcade/application.py", line 71, in __init__
    resizable=resizable, config=config, vsync=False)
  File "/home/lamartire/.local/share/virtualenvs/o5_25-5__1sqhq/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 165, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/lamartire/.local/share/virtualenvs/o5_25-5__1sqhq/lib/python3.7/site-packages/pyglet/window/__init__.py", line 580, in __init__
    config = screen.get_best_config(config)
  File "/home/lamartire/.local/share/virtualenvs/o5_25-5__1sqhq/lib/python3.7/site-packages/pyglet/canvas/base.py", line 192, in get_best_config
    raise window.NoSuchConfigException()
pyglet.window.NoSuchConfigException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 82, in <module>
    main()
  File "main.py", line 76, in main
    game = MyGame(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)
  File "main.py", line 27, in __init__
    super().__init__(width, height, title)
  File "/home/lamartire/.local/share/virtualenvs/o5_25-5__1sqhq/lib/python3.7/site-packages/arcade/application.py", line 73, in __init__
    raise NoOpenGLException("Unable to create an OpenGL 3.3+ context. "
arcade.application.NoOpenGLException: Unable to create an OpenGL 3.3+ context. Check to make sure your system supports OpenGL 3.3 or higher.
```

**Comment by einarf** [comment]
Try this to disable antialiasing. That is a common reason for this issue.
```
game = MyGame(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE, antialiasing=False)
```

**Comment by lamartire** [comment]
@einarf it does not help :disappointed:

**Comment by einarf** [comment]
* What exact example are you running?
* What version of arcade?
* What version of pyglet installled?

**Comment by lamartire** [comment]
- [This example](https://arcade.academy/examples/starting_template.html#starting-template)
- `arcade ==2.3.14`
- `pyglet ==2.0.dev0`

**Comment by einarf** [comment]
Try downgrading to latest pyglet 1.5.x

**Comment by lamartire** [comment]
Nothing is changed. Trying pyglet `1.5.3`

**Comment by einarf** [comment]
I still suspect this is antialiasing. Try hard-overriding in constructor.
```python
    def __init__(self, width, height, title):
        super().__init__(width, height, title, antialiasing=False)
```

**Comment by lamartire** [comment]
Already did that :)

**Comment by einarf** [comment]
hmm weird. You can try to query opengl viersion with moderngl maybe
```
> pip install moderngl==5,5,4
> python -m moderngl
```
What does this return for you?

**Comment by einarf** [comment]
Wait. Are you running Wayland? That can be a problem.

**Comment by lamartire** [comment]
Yes, I'm on wayland.

**Comment by einarf** [comment]
This could be a pyglet issue : https://github.com/pyglet/pyglet

**Comment by benmoran56** [comment]
Could you post the output of `python -m pyglet.info` ?

To use under Wayland you will need the proper packages installed for Xwayland support, as pyglet does not yet support native Wayland.

**Comment by lamartire** [comment]
Here is an output:

```
Platform
------------------------------------------------------------------------------
platform:  Linux-5.5.8-200.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
release:   5.5.8-200.fc31.x86_64
machine:   x86_64

Python
------------------------------------------------------------------------------
implementation: CPython
sys.version: 3.7.6 (default, Jan 30 2020, 09:44:41) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
sys.maxint: 9223372036854775807
os.getcwd(): /home/lamartire/Github/o5_25

pyglet
------------------------------------------------------------------------------
pyglet.version: 1.5.3
pyglet.compat_platform: linux
pyglet.__file__: /home/lamartire/.local/share/virtualenvs/o5_25-5__1sqhq/lib/python3.7/site-packages/pyglet/__init__.py
pyglet.options['audio'] = ('directsound', 'openal', 'pulse', 'silent')
pyglet.options['debug_font'] = False
pyglet.options['debug_gl'] = True
pyglet.options['debug_gl_trace'] = False
pyglet.options['debug_gl_trace_args'] = False
pyglet.options['debug_graphics_batch'] = False
pyglet.options['debug_lib'] = False
pyglet.options['debug_media'] = False
pyglet.options['debug_texture'] = False
pyglet.options['debug_trace'] = False
pyglet.options['debug_trace_args'] = False
pyglet.options['debug_trace_depth'] = 1
pyglet.options['debug_trace_flush'] = True
pyglet.options['debug_win32'] = False
pyglet.options['debug_x11'] = False
pyglet.options['graphics_vbo'] = True
pyglet.options['shadow_window'] = True
pyglet.options['vsync'] = None
pyglet.options['xsync'] = True
pyglet.options['xlib_fullscreen_override_redirect'] = False
pyglet.options['darwin_cocoa'] = True
pyglet.options['search_local_libs'] = True

pyglet.window
------------------------------------------------------------------------------
display: <pyglet.canvas.xlib.XlibDisplay object at 0x7f6563358c50>
screens[0]: XlibScreen(display=<pyglet.canvas.xlib.XlibDisplay object at 0x7f6563358c50>, x=0, y=0, width=1920, height=1080, xinerama=0)
config['double_buffer'] = 1
config['stereo'] = 0
config['buffer_size'] = 24
config['aux_buffers'] = 0
config['sample_buffers'] = 0
config['samples'] = 0
config['red_size'] = 8
config['green_size'] = 8
config['blue_size'] = 8
config['alpha_size'] = 0
config['depth_size'] = 24
config['stencil_size'] = 0
config['accum_red_size'] = 0
config['accum_green_size'] = 0
config['accum_blue_size'] = 0
config['accum_alpha_size'] = 0
config['major_version'] = None
config['minor_version'] = None
config['forward_compatible'] = None
config['debug'] = None
context: XlibContextARB()

window.context._info
------------------------------------------------------------------------------
gl_info.get_version(): 4.5 (Compatibility Profile) Mesa 19.2.8
gl_info.get_vendor(): X.Org
gl_info.get_renderer(): AMD RAVEN (DRM 3.36.0, 5.5.8-200.fc31.x86_64, LLVM 9.0.0)
gl_info.get_extensions():
   GL_AMD_conservative_depth
   GL_AMD_depth_clamp_separate
   GL_AMD_draw_buffers_blend
   GL_AMD_framebuffer_multisample_advanced
   GL_AMD_multi_draw_indirect
   GL_AMD_performance_monitor
   GL_AMD_pinned_memory
   GL_AMD_query_buffer_object
   GL_AMD_seamless_cubemap_per_texture
   GL_AMD_shader_stencil_export
   GL_AMD_shader_trinary_minmax
   GL_AMD_texture_texture4
   GL_AMD_vertex_shader_layer
   GL_AMD_vertex_shader_viewport_index
   GL_ANGLE_texture_compression_dxt3
   GL_ANGLE_texture_compression_dxt5
   GL_APPLE_packed_pixels
   GL_ARB_ES2_compatibility
   GL_ARB_ES3_1_compatibility
   GL_ARB_ES3_compatibility
   GL_ARB_arrays_of_arrays
   GL_ARB_base_instance
   GL_ARB_bindless_texture
   GL_ARB_blend_func_extended
   GL_ARB_buffer_storage
   GL_ARB_clear_buffer_object
   GL_ARB_clear_texture
   GL_ARB_clip_control
   GL_ARB_color_buffer_float
   GL_ARB_compatibility
   GL_ARB_compressed_texture_pixel_storage
   GL_ARB_compute_shader
   GL_ARB_compute_variable_group_size
   GL_ARB_conditional_render_inverted
   GL_ARB_conservative_depth
   GL_ARB_copy_buffer
   GL_ARB_copy_image
   GL_ARB_cull_distance
   GL_ARB_debug_output
   GL_ARB_depth_buffer_float
   GL_ARB_depth_clamp
   GL_ARB_depth_texture
   GL_ARB_derivative_control
   GL_ARB_direct_state_access
   GL_ARB_draw_buffers
   GL_ARB_draw_buffers_blend
   GL_ARB_draw_elements_base_vertex
   GL_ARB_draw_indirect
   GL_ARB_draw_instanced
   GL_ARB_enhanced_layouts
   GL_ARB_explicit_attrib_location
   GL_ARB_explicit_uniform_location
   GL_ARB_fragment_coord_conventions
   GL_ARB_fragment_layer_viewport
   GL_ARB_fragment_program
   GL_ARB_fragment_program_shadow
   GL_ARB_fragment_shader
   GL_ARB_framebuffer_no_attachments
   GL_ARB_framebuffer_object
   GL_ARB_framebuffer_sRGB
   GL_ARB_get_program_binary
   GL_ARB_get_texture_sub_image
   GL_ARB_gpu_shader5
   GL_ARB_gpu_shader_fp64
   GL_ARB_half_float_pixel
   GL_ARB_half_float_vertex
   GL_ARB_indirect_parameters
   GL_ARB_instanced_arrays
   GL_ARB_internalformat_query
   GL_ARB_internalformat_query2
   GL_ARB_invalidate_subdata
   GL_ARB_map_buffer_alignment
   GL_ARB_map_buffer_range
   GL_ARB_multi_bind
   GL_ARB_multi_draw_indirect
   GL_ARB_multisample
   GL_ARB_multitexture
   GL_ARB_occlusion_query
   GL_ARB_occlusion_query2
   GL_ARB_parallel_shader_compile
   GL_ARB_pipeline_statistics_query
   GL_ARB_pixel_buffer_object
   GL_ARB_point_parameters
   GL_ARB_point_sprite
   GL_ARB_polygon_offset_clamp
   GL_ARB_program_interface_query
   GL_ARB_provoking_vertex
   GL_ARB_query_buffer_object
   GL_ARB_robust_buffer_access_behavior
   GL_ARB_robustness
   GL_ARB_sample_shading
   GL_ARB_sampler_objects
   GL_ARB_seamless_cube_map
   GL_ARB_seamless_cubemap_per_texture
   GL_ARB_separate_shader_objects
   GL_ARB_shader_atomic_counter_ops
   GL_ARB_shader_atomic_counters
   GL_ARB_shader_ballot
   GL_ARB_shader_bit_encoding
   GL_ARB_shader_clock
   GL_ARB_shader_draw_parameters
   GL_ARB_shader_group_vote
   GL_ARB_shader_image_load_store
   GL_ARB_shader_image_size
   GL_ARB_shader_objects
   GL_ARB_shader_precision
   GL_ARB_shader_stencil_export
   GL_ARB_shader_storage_buffer_object
   GL_ARB_shader_subroutine
   GL_ARB_shader_texture_image_samples
   GL_ARB_shader_texture_lod
   GL_ARB_shader_viewport_layer_array
   GL_ARB_shading_language_100
   GL_ARB_shading_language_420pack
   GL_ARB_shading_language_packing
   GL_ARB_shadow
   GL_ARB_stencil_texturing
   GL_ARB_sync
   GL_ARB_tessellation_shader
   GL_ARB_texture_barrier
   GL_ARB_texture_border_clamp
   GL_ARB_texture_buffer_object
   GL_ARB_texture_buffer_object_rgb32
   GL_ARB_texture_buffer_range
   GL_ARB_texture_compression
   GL_ARB_texture_compression_bptc
   GL_ARB_texture_compression_rgtc
   GL_ARB_texture_cube_map
   GL_ARB_texture_cube_map_array
   GL_ARB_texture_env_add
   GL_ARB_texture_env_combine
   GL_ARB_texture_env_crossbar
   GL_ARB_texture_env_dot3
   GL_ARB_texture_filter_anisotropic
   GL_ARB_texture_float
   GL_ARB_texture_gather
   GL_ARB_texture_mirror_clamp_to_edge
   GL_ARB_texture_mirrored_repeat
   GL_ARB_texture_multisample
   GL_ARB_texture_non_power_of_two
   GL_ARB_texture_query_levels
   GL_ARB_texture_query_lod
   GL_ARB_texture_rectangle
   GL_ARB_texture_rg
   GL_ARB_texture_rgb10_a2ui
   GL_ARB_texture_stencil8
   GL_ARB_texture_storage
   GL_ARB_texture_storage_multisample
   GL_ARB_texture_swizzle
   GL_ARB_texture_view
   GL_ARB_timer_query
   GL_ARB_transform_feedback2
   GL_ARB_transform_feedback3
   GL_ARB_transform_feedback_instanced
   GL_ARB_transform_feedback_overflow_query
   GL_ARB_transpose_matrix
   GL_ARB_uniform_buffer_object
   GL_ARB_vertex_array_bgra
   GL_ARB_vertex_array_object
   GL_ARB_vertex_attrib_64bit
   GL_ARB_vertex_attrib_binding
   GL_ARB_vertex_buffer_object
   GL_ARB_vertex_program
   GL_ARB_vertex_shader
   GL_ARB_vertex_type_10f_11f_11f_rev
   GL_ARB_vertex_type_2_10_10_10_rev
   GL_ARB_viewport_array
   GL_ARB_window_pos
   GL_ATI_blend_equation_separate
   GL_ATI_draw_buffers
   GL_ATI_fragment_shader
   GL_ATI_meminfo
   GL_ATI_separate_stencil
   GL_ATI_texture_compression_3dc
   GL_ATI_texture_env_combine3
   GL_ATI_texture_float
   GL_ATI_texture_mirror_once
   GL_EXT_abgr
   GL_EXT_bgra
   GL_EXT_blend_color
   GL_EXT_blend_equation_separate
   GL_EXT_blend_func_separate
   GL_EXT_blend_minmax
   GL_EXT_blend_subtract
   GL_EXT_compiled_vertex_array
   GL_EXT_copy_texture
   GL_EXT_depth_bounds_test
   GL_EXT_draw_buffers2
   GL_EXT_draw_instanced
   GL_EXT_draw_range_elements
   GL_EXT_fog_coord
   GL_EXT_framebuffer_blit
   GL_EXT_framebuffer_multisample
   GL_EXT_framebuffer_multisample_blit_scaled
   GL_EXT_framebuffer_object
   GL_EXT_framebuffer_sRGB
   GL_EXT_gpu_program_parameters
   GL_EXT_gpu_shader4
   GL_EXT_memory_object
   GL_EXT_memory_object_fd
   GL_EXT_multi_draw_arrays
   GL_EXT_packed_depth_stencil
   GL_EXT_packed_float
   GL_EXT_packed_pixels
   GL_EXT_pixel_buffer_object
   GL_EXT_point_parameters
   GL_EXT_polygon_offset_clamp
   GL_EXT_provoking_vertex
   GL_EXT_rescale_normal
   GL_EXT_secondary_color
   GL_EXT_semaphore
   GL_EXT_semaphore_fd
   GL_EXT_separate_specular_color
   GL_EXT_shader_image_load_formatted
   GL_EXT_shader_integer_mix
   GL_EXT_shadow_funcs
   GL_EXT_stencil_two_side
   GL_EXT_stencil_wrap
   GL_EXT_subtexture
   GL_EXT_texture
   GL_EXT_texture3D
   GL_EXT_texture_array
   GL_EXT_texture_buffer_object
   GL_EXT_texture_compression_dxt1
   GL_EXT_texture_compression_latc
   GL_EXT_texture_compression_rgtc
   GL_EXT_texture_compression_s3tc
   GL_EXT_texture_cube_map
   GL_EXT_texture_edge_clamp
   GL_EXT_texture_env_add
   GL_EXT_texture_env_combine
   GL_EXT_texture_env_dot3
   GL_EXT_texture_filter_anisotropic
   GL_EXT_texture_integer
   GL_EXT_texture_lod_bias
   GL_EXT_texture_mirror_clamp
   GL_EXT_texture_object
   GL_EXT_texture_rectangle
   GL_EXT_texture_sRGB
   GL_EXT_texture_sRGB_R8
   GL_EXT_texture_sRGB_decode
   GL_EXT_texture_shared_exponent
   GL_EXT_texture_snorm
   GL_EXT_texture_swizzle
   GL_EXT_timer_query
   GL_EXT_transform_feedback
   GL_EXT_vertex_array
   GL_EXT_vertex_array_bgra
   GL_EXT_vertex_attrib_64bit
   GL_EXT_window_rectangles
   GL_IBM_multimode_draw_arrays
   GL_IBM_rasterpos_clip
   GL_IBM_texture_mirrored_repeat
   GL_INGR_blend_func_separate
   GL_KHR_blend_equation_advanced
   GL_KHR_context_flush_control
   GL_KHR_debug
   GL_KHR_no_error
   GL_KHR_parallel_shader_compile
   GL_KHR_robust_buffer_access_behavior
   GL_KHR_robustness
   GL_KHR_texture_compression_astc_ldr
   GL_KHR_texture_compression_astc_sliced_3d
   GL_MESA_pack_invert
   GL_MESA_shader_integer_functions
   GL_MESA_texture_signed_rgba
   GL_MESA_window_pos
   GL_NVX_gpu_memory_info
   GL_NV_blend_square
   GL_NV_conditional_render
   GL_NV_depth_clamp
   GL_NV_fog_distance
   GL_NV_light_max_exponent
   GL_NV_packed_depth_stencil
   GL_NV_primitive_restart
   GL_NV_texgen_reflection
   GL_NV_texture_barrier
   GL_NV_texture_env_combine4
   GL_NV_texture_rectangle
   GL_NV_vdpau_interop
   GL_OES_EGL_image
   GL_OES_read_format
   GL_S3_s3tc
   GL_SGIS_generate_mipmap
   GL_SGIS_texture_border_clamp
   GL_SGIS_texture_edge_clamp
   GL_SGIS_texture_lod
   GL_SUN_multi_draw_arrays

pyglet.gl.glu_info
------------------------------------------------------------------------------
glu_info.get_version(): 1.3
glu_info.get_extensions():
   GLU_EXT_nurbs_tessellator
   GLU_EXT_object_space_tess

pyglet.gl.glx_info
------------------------------------------------------------------------------
context.is_direct(): 1
glx_info.get_server_vendor(): SGI
glx_info.get_server_version(): 1.4
glx_info.get_server_extensions():
   GLX_ARB_context_flush_control
   GLX_ARB_create_context
   GLX_ARB_create_context_no_error
   GLX_ARB_create_context_profile
   GLX_ARB_fbconfig_float
   GLX_ARB_framebuffer_sRGB
   GLX_ARB_multisample
   GLX_EXT_create_context_es_profile
   GLX_EXT_create_context_es2_profile
   GLX_EXT_fbconfig_packed_float
   GLX_EXT_framebuffer_sRGB
   GLX_EXT_import_context
   GLX_EXT_libglvnd
   GLX_EXT_no_config_context
   GLX_EXT_texture_from_pixmap
   GLX_EXT_visual_info
   GLX_EXT_visual_rating
   GLX_MESA_copy_sub_buffer
   GLX_OML_swap_method
   GLX_SGI_make_current_read
   GLX_SGIS_multisample
   GLX_SGIX_fbconfig
   GLX_SGIX_pbuffer
   GLX_SGIX_visual_select_group
glx_info.get_client_vendor(): Mesa Project and SGI
glx_info.get_client_version(): 1.4
glx_info.get_client_extensions():
   GLX_ARB_context_flush_control
   GLX_ARB_create_context
   GLX_ARB_create_context_no_error
   GLX_ARB_create_context_profile
   GLX_ARB_create_context_robustness
   GLX_ARB_fbconfig_float
   GLX_ARB_framebuffer_sRGB
   GLX_ARB_get_proc_address
   GLX_ARB_multisample
   GLX_EXT_buffer_age
   GLX_EXT_create_context_es2_profile
   GLX_EXT_create_context_es_profile
   GLX_EXT_fbconfig_packed_float
   GLX_EXT_framebuffer_sRGB
   GLX_EXT_import_context
   GLX_EXT_texture_from_pixmap
   GLX_EXT_visual_info
   GLX_EXT_visual_rating
   GLX_INTEL_swap_event
   GLX_MESA_copy_sub_buffer
   GLX_MESA_multithread_makecurrent
   GLX_MESA_query_renderer
   GLX_MESA_swap_control
   GLX_OML_swap_method
   GLX_OML_sync_control
   GLX_SGIS_multisample
   GLX_SGIX_fbconfig
   GLX_SGIX_pbuffer
   GLX_SGIX_visual_select_group
   GLX_SGI_make_current_read
   GLX_SGI_swap_control
   GLX_SGI_video_sync
glx_info.get_extensions():
   GLX_ARB_create_context
   GLX_ARB_create_context_no_error
   GLX_ARB_create_context_profile
   GLX_ARB_fbconfig_float
   GLX_ARB_framebuffer_sRGB
   GLX_ARB_get_proc_address
   GLX_ARB_multisample
   GLX_EXT_buffer_age
   GLX_EXT_create_context_es2_profile
   GLX_EXT_create_context_es_profile
   GLX_EXT_fbconfig_packed_float
   GLX_EXT_framebuffer_sRGB
   GLX_EXT_import_context
   GLX_EXT_texture_from_pixmap
   GLX_EXT_visual_info
   GLX_EXT_visual_rating
   GLX_MESA_copy_sub_buffer
   GLX_MESA_query_renderer
   GLX_MESA_swap_control
   GLX_OML_swap_method
   GLX_OML_sync_control
   GLX_SGIS_multisample
   GLX_SGIX_fbconfig
   GLX_SGIX_pbuffer
   GLX_SGIX_visual_select_group
   GLX_SGI_make_current_read
   GLX_SGI_video_sync

pyglet.media
------------------------------------------------------------------------------
audio driver: <pyglet.media.drivers.openal.adaptation.OpenALDriver object at 0x7f6517348f90>

pyglet.media.ffmpeg
------------------------------------------------------------------------------
FFmpeg version: 4.2.2

pyglet.media.drivers.openal
------------------------------------------------------------------------------
Library: <CDLL 'libopenal.so.1', handle 56204663d9b0 at 0x7f651734e790>
Version: 1.1
Extensions:
   ALC_ENUMERATE_ALL_EXT
   ALC_ENUMERATION_EXT
   ALC_EXT_CAPTURE
   ALC_EXT_DEDICATED
   ALC_EXT_disconnect
   ALC_EXT_EFX
   ALC_EXT_thread_local_context
   ALC_SOFT_device_clock
   ALC_SOFT_HRTF
   ALC_SOFT_loopback
   ALC_SOFT_output_limiter
   ALC_SOFT_pause_device

pyglet.input.wintab
------------------------------------------------------------------------------
WinTab not available.
```

**Comment by benmoran56** [comment]
That looks like it should work. Can you try this simple example with pyglet? 

```py
import pyglet

window = pyglet.window.Window()


@window.event
def on_draw():
    window.clear()


pyglet.app.run()
```

**Comment by lamartire** [comment]
@benmoran56 this snippet works without exceptions

**Comment by einarf** [comment]
So I guess it fails with core context config (even without shadow window):
```python
import pyglet
pyglet.options['shadow_window'] = False

config = pyglet.gl.Config(major_version=3, minor_version=3, double_buffer=True)
window = pyglet.window.Window(config=config)

@window.event
def on_draw():
    window.clear()

pyglet.app.run()
```

**Comment by benmoran56** [comment]
I was going to suggest that same test :+1: 
That should just be calling `glXChooseFBConfig` with only the passed major/minor versions, so it's pretty straightforward. 

This isn't a VM by chance, is it? If not, what is the graphics hardware?

**Comment by einarf** [comment]
Looking at this ...
```
gl_info.get_version(): 4.5 (Compatibility Profile) Mesa 19.2.8
gl_info.get_vendor(): X.Org
gl_info.get_renderer(): AMD RAVEN (DRM 3.36.0, 5.5.8-200.fc31.x86_64, LLVM 9.0.0)
```
... you would be able to use arcade by removing the `config` passed to the window. It's already a 4.5 compatibility profile. More than enough.

**Comment by einarf** [comment]
It this maybe also related to shadow window being disabled on linux? Maybe we should only do that for darwin.

**Comment by benmoran56** [comment]
From what I understand, on MESA you'll just get whatever the highest profile available, regardless of what you request (if it's a modern profile).

**Comment by benmoran56** [comment]
@lamartire I should have asked before, but just for sanity sake, could you try those test snippets **einarf** and myself posted on both pyglet 1.5.x, **and** pyglet 2.0dev?

**Comment by lamartire** [comment]
@benmoran56 I'm sorry, have a very busy week. I certainly will try it in a few days :)

**Comment by benmoran56** [comment]
No worries! I was able to confirm it on my machine with a Wayland session. It seems to be antialiasing related, so I would expect that those snippets would probably work OK for you. In the mean time I think we have something to investigate.

**Comment by anthonyarusso** [comment]
I believe I am experiencing a similar issue within Debian 10 (running within a ChromeOS 'Crostini' container). I read through the thread above and tested the snippets provided with Pyglet 1.5.11. Changing the OpenGL version inside the Config() function to anything higher than 3.1 causes an error, but otherwise they will run successfully.

Has any solution been found for this yet?

Edit: Installed Pyglet 2.0 dev and tested the snippets again. Behavior seems to be the same as 1.5.11.
Also, using `xeyes` it appears that my window is running on XServer (or perhaps XWayland) rather than Wayland.

**Comment by pvcraven** [comment]
What do you get if you type in:
`glxinfo | grep "OpenGL version"`

**Comment by anthonyarusso** [comment]
OpenGL Version string: 3.1 Mesa 19.2.8.
I was lead to believe this was different from my OpenGL core profile version string which is 4.3. Based on your response I now suspect I'm simply running outdated drivers.

**Comment by pvcraven** [comment]
Closing this, unless we can narrow things down.
