### ISSUE TITLE
Manjaro issue running template

### ISSUE THREAD

**Issue by GregTheHun** [pythonarcade/arcade#693]
### Actual behavior:
It appears after following the install instructions from the install page, it gives me an error using the window class template in the docs.

### Expected behavior:
Running as expected, given the example.

### Steps to reproduce/example code:
Install arcade library in venv for Python 3.8.2
Copy code
Run code in venv
(Information such as os info from /etc/*-release, etc. is below)

#### cat /etc/*-release
```
Manjaro Linux
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=20.0.1
DISTRIB_CODENAME=Lysia
DISTRIB_DESCRIPTION="Manjaro Linux"
Manjaro Linux
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.manjaro.org/"
SUPPORT_URL="https://www.manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```

#### pip list (under venv)
```
Package        Version
-------------- -------
arcade         2.3.15
attrs          19.3.0
flake8         3.8.2
mccabe         0.6.1
numpy          1.18.4
Pillow         7.1.2
pip            20.1.1
pycodestyle    2.6.0
pyflakes       2.2.0
pyglet         1.5.5
pytiled-parser 0.9.3
setuptools     46.4.0
```

#### Code used to run it in venv
```
#!/usr/bin/env python  <--- The only thing I added from the template

"""
Starting Template

Once you have learned how to use classes, you can begin your program with this
template.

If Python and Arcade are installed, this example can be run from the command line with:
python -m arcade.examples.starting_template
"""
import arcade

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "Starting Template"


class MyGame(arcade.Window):
    """
    Main application class.

    NOTE: Go ahead and delete the methods you don't need.
    If you do need a method, delete the 'pass' and replace it
    with your own code. Don't leave 'pass' in this program.
    """

    def __init__(self, width, height, title):
        super().__init__(width, height, title)

        arcade.set_background_color(arcade.color.AMAZON)

        # If you have sprite lists, you should create them here,
        # and set them to None

    def setup(self):
        # Create your sprites and sprite lists here
        pass

    def on_draw(self):
        """
        Render the screen.
        """

        # This command should happen before we start drawing. It will clear
        # the screen to the background color, and erase what we drew last frame.
        arcade.start_render()

        # Call draw() on all your sprite lists below

    def on_update(self, delta_time):
        """
        All the logic to move, and the game logic goes here.
        Normally, you'll call update() on the sprite lists that
        need it.
        """
        pass

    def on_key_press(self, key, key_modifiers):
        """
        Called whenever a key on the keyboard is pressed.

        For a full list of keys, see:
        http://arcade.academy/arcade.key.html
        """
        pass

    def on_key_release(self, key, key_modifiers):
        """
        Called whenever the user lets off a previously pressed key.
        """
        pass

    def on_mouse_motion(self, x, y, delta_x, delta_y):
        """
        Called whenever the mouse moves.
        """
        pass

    def on_mouse_press(self, x, y, button, key_modifiers):
        """
        Called when the user presses a mouse button.
        """
        pass

    def on_mouse_release(self, x, y, button, key_modifiers):
        """
        Called when a user releases a mouse button.
        """
        pass


def main():
    """ Main method """
    game = MyGame(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)
    game.setup()
    arcade.run()


if __name__ == "__main__":
    main()
```

**Comment by pvcraven** [comment]
What error do you get?

**Comment by GregTheHun** [comment]
```
(testArcade) greg@manjaro:~/g/p/g/firstGame|master⚡*?
➤ ./main.py
fish: “./main.py” terminated by signal SIGILL (Illegal instruction)
```

**Comment by pvcraven** [comment]
Are you able to create a simple pyglet window?
```
import pyglet

# create a pyglet window
win = pyglet.window.Window()

# run our pyglet app, and show the window
pyglet.app.run()
```

**Comment by GregTheHun** [comment]
Yep, basic black window

**Comment by pvcraven** [comment]
Ok. Not sure how easy it is for you to modify the packages (for example, PyCharm makes it pretty easy) but logging or printing to trace into Window.__init__ (or wherever it takes you) to figure out where it is seg faulting would be helpful.

**Comment by GregTheHun** [comment]
I use VS Code if that can give us a path to print the trace

**Comment by pvcraven** [comment]
I suggest using the debugger and tracing through the code to narrow down where the crash occurs.

**Comment by GregTheHun** [comment]
It seems to occur at the import of arcade

**Comment by einarf** [comment]
This is relevant? : https://github.com/pyglet/pyglet/issues/206

**Comment by pvcraven** [comment]
Interesting. Not where I would have guessed. You can trace into the import
to narrow it down even further.

Paul Vincent Craven

**Comment by GregTheHun** [comment]
This seems to be the only information I can get out of debugging the code:
```
greg@manjaro:~/g/python-code|master⚡*?
➤ source /home/greg/venv/testArcade/bin/activate.fish
(testArcade) greg@manjaro:~/g/python-code|master⚡*?
➤  env /home/greg/venv/testArcade/bin/python /home/greg/.vscode/extensions/ms-python.python-2020.5.80290/pythonFiles/lib/python/debugpy/no_wheels/debugpy/launcher 44633 -- /home/greg/git/python-code/games/firstGame/main.py 
```

**Comment by einarf** [comment]
I'm guessing it doesn't like the 3.3 core initialization. It might be replicated by this snippet: https://github.com/pvcraven/arcade/issues/635#issuecomment-613366258

**Comment by GregTheHun** [comment]
Sorry for the late response, but I tried that code:
```
#!/usr/bin/env python

import pyglet
pyglet.options['shadow_window'] = False

config = pyglet.gl.Config(major_version=3, minor_version=3, double_buffer=True)
window = pyglet.window.Window(config=config)

@window.event
def on_draw():
    window.clear()

pyglet.app.run()
```

With the "pyglet.options['shadow_window'] = False" line:
```
Traceback (most recent call last):
  File "test2.py", line 13, in <module>
    pyglet.app.run()
  File "/home/greg/venv/testArcade/lib/python3.8/site-packages/pyglet/app/__init__.py", line 107, in run
    event_loop.run()
  File "/home/greg/venv/testArcade/lib/python3.8/site-packages/pyglet/app/base.py", line 159, in run
    self._legacy_setup()
  File "/home/greg/venv/testArcade/lib/python3.8/site-packages/pyglet/app/base.py", line 182, in _legacy_setup
    window.dispatch_pending_events()
  File "/home/greg/venv/testArcade/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 959, in dispatch_pending_events
    EventDispatcher.dispatch_event(self, *self._event_queue.pop(0))
  File "/home/greg/venv/testArcade/lib/python3.8/site-packages/pyglet/event.py", line 550, in dispatch_event
    if handler(*args):
  File "/home/greg/venv/testArcade/lib/python3.8/site-packages/pyglet/window/__init__.py", line 810, in on_resize
    self._projection.set(width, height, *self.get_framebuffer_size())
  File "/home/greg/venv/testArcade/lib/python3.8/site-packages/pyglet/window/__init__.py", line 274, in set
    gl.glMatrixMode(gl.GL_PROJECTION)
  File "/home/greg/venv/testArcade/lib/python3.8/site-packages/pyglet/gl/lib.py", line 107, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid operation'
```

And without that line:
```
Traceback (most recent call last):
  File "test2.py", line 13, in <module>
    pyglet.app.run()
  File "/home/greg/venv/testArcade/lib/python3.8/site-packages/pyglet/app/__init__.py", line 107, in run
    event_loop.run()
  File "/home/greg/venv/testArcade/lib/python3.8/site-packages/pyglet/app/base.py", line 159, in run
    self._legacy_setup()
  File "/home/greg/venv/testArcade/lib/python3.8/site-packages/pyglet/app/base.py", line 182, in _legacy_setup
    window.dispatch_pending_events()
  File "/home/greg/venv/testArcade/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 959, in dispatch_pending_events
    EventDispatcher.dispatch_event(self, *self._event_queue.pop(0))
  File "/home/greg/venv/testArcade/lib/python3.8/site-packages/pyglet/event.py", line 550, in dispatch_event
    if handler(*args):
  File "/home/greg/venv/testArcade/lib/python3.8/site-packages/pyglet/window/__init__.py", line 810, in on_resize
    self._projection.set(width, height, *self.get_framebuffer_size())
  File "/home/greg/venv/testArcade/lib/python3.8/site-packages/pyglet/window/__init__.py", line 274, in set
    gl.glMatrixMode(gl.GL_PROJECTION)
  File "/home/greg/venv/testArcade/lib/python3.8/site-packages/pyglet/gl/lib.py", line 107, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid operation'
```

Both kill the window immediately with the errors above.

**Comment by einarf** [comment]
Ok. So that does mean you managed to create a 3.3 core context. The `GLException` is expected in this situation. Did you try with arcade 2.4a9 instead of 2.3.*?

**Comment by einarf** [comment]
Closing for now. No more input from the author. Be free to re-open if you have more information
