### ISSUE TITLE
Tetris example game bug / edge case

### ISSUE THREAD

**Issue by vesche** [pythonarcade/arcade#795]
## Bug Report

In the example games, Tetris has a bug. Certain game pieces when moved to the edge of the game window and then rotated will attempt to clip outside of the game window causing an `IndexError: list index out of range`

### Actual behavior:

![2020-11-28-235513_354x426_scrot](https://user-images.githubusercontent.com/8083281/100534501-33b18880-31d5-11eb-967e-79b5c61db3bd.png)

^ Traceback when rotated from this position:

```
Traceback (most recent call last):
  File "tetris.py", line 282, in <module>
    main()
  File "tetris.py", line 278, in main
    arcade.run()
  File "/home/user/.local/lib/python3.8/site-packages/arcade/window_commands.py", line 236, in run
    pyglet.app.run()
  File "/home/user/.local/lib/python3.8/site-packages/pyglet/app/__init__.py", line 107, in run
    event_loop.run()
  File "/home/user/.local/lib/python3.8/site-packages/pyglet/app/base.py", line 168, in run
    platform_event_loop.step(timeout)
  File "/home/user/.local/lib/python3.8/site-packages/pyglet/app/xlib.py", line 121, in step
    device.select()
  File "/home/user/.local/lib/python3.8/site-packages/pyglet/canvas/xlib.py", line 205, in select
    dispatch(e)
  File "/home/user/.local/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 974, in dispatch_platform_event
    event_handler(e)
  File "/home/user/.local/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 1162, in _event_key
    return self._event_key_view(ev)
  File "/home/user/.local/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 1143, in _event_key_view
    self.dispatch_event('on_key_press', symbol, modifiers)
  File "/home/user/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 1333, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "/home/user/.local/lib/python3.8/site-packages/pyglet/event.py", line 415, in dispatch_event
    if getattr(self, event_type)(*args):
  File "tetris.py", line 232, in on_key_press
    self.rotate_stone()
  File "tetris.py", line 199, in rotate_stone
    if not check_collision(self.board, new_stone, (self.stone_x, self.stone_y)):
  File "tetris.py", line 92, in check_collision
    if cell and board[cy + off_y][cx + off_x]:
IndexError: list index out of range
```

### Expected behavior:

Looks as if most other tetris implementations will allow the rotation, but pop it to fit in the game window.

### Steps to reproduce/example code:

`python arcade/examples/tetris.py` get a game piece that would rotate past the edge of the game window and try it.

**Comment by einarf** [comment]
Already merged and released. Closing
