### ISSUE TITLE
arcade.run() raises GLException: b'invalid operation'

### ISSUE THREAD

**Issue by NH-VII** [pythonarcade/arcade#808]
I'm trying to migrate a pygame project on arcade but I'm stuck at the very beginning:
Arcade.run() raises a pyglet.gl.lib.GLException: b'invalid operation'

I'm using:
- Windows 10
- python 3.8.7 (in a fresh venv with only arcade package installed)
- arcade 2.5.1

Maybe i'm missing something basic.

my python code (from "arcade.academy: How to Draw with Your Computer"):
```python
import arcade

arcade.open_window(600, 600, "Drawing Example")

# Set the background color
arcade.set_background_color(arcade.csscolor.SKY_BLUE)

# Get ready to draw
arcade.start_render()

# (The drawing code will go here.)
arcade.draw_lrtb_rectangle_filled(0, 599, 300, 0, arcade.csscolor.GREEN)
# Finish drawing
arcade.finish_render()

# Keep the window up until someone closes it.
arcade.run()
```
the error:
```
Traceback (most recent call last):
  File "C:\Users\riccardo\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\riccardo\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\riccardo\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\riccardo\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\riccardo\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\riccardo\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\riccardo\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\riccardo\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\riccardo\Documents\Python\gameAI\main.py", line 17, in <module>
    arcade.run()
  File "c:\Users\riccardo\Documents\Python\gameAI\gameAI_venv\lib\site-packages\arcade\window_commands.py", line 236, in run
    pyglet.app.run()
  File "c:\Users\riccardo\Documents\Python\gameAI\gameAI_venv\lib\site-packages\pyglet\app\__init__.py", line 107, in run
    event_loop.run()
  File "c:\Users\riccardo\Documents\Python\gameAI\gameAI_venv\lib\site-packages\pyglet\app\base.py", line 159, in run
    self._legacy_setup()
  File "c:\Users\riccardo\Documents\Python\gameAI\gameAI_venv\lib\site-packages\pyglet\app\base.py", line 182, in _legacy_setup
    window.dispatch_pending_events()
  File "c:\Users\riccardo\Documents\Python\gameAI\gameAI_venv\lib\site-packages\pyglet\window\win32\__init__.py", line 709, in dispatch_pending_events
    EventDispatcher.dispatch_event(self, *event)
  File "c:\Users\riccardo\Documents\Python\gameAI\gameAI_venv\lib\site-packages\pyglet\event.py", line 415, in dispatch_event
    if getattr(self, event_type)(*args):
  File "c:\Users\riccardo\Documents\Python\gameAI\gameAI_venv\lib\site-packages\arcade\application.py", line 356, in on_resize
    self.set_viewport(original_viewport[0],
  File "c:\Users\riccardo\Documents\Python\gameAI\gameAI_venv\lib\site-packages\arcade\application.py", line 434, in set_viewport
    set_viewport(left, right, bottom, top)
  File "c:\Users\riccardo\Documents\Python\gameAI\gameAI_venv\lib\site-packages\arcade\window_commands.py", line 179, in set_viewport
    fbo.viewport = 0, 0, int(window.width * scaling), int(window.height * scaling)
  File "c:\Users\riccardo\Documents\Python\gameAI\gameAI_venv\lib\site-packages\arcade\gl\framebuffer.py", line 180, in viewport
    gl.glViewport(*self._viewport)
  File "c:\Users\riccardo\Documents\Python\gameAI\gameAI_venv\lib\site-packages\pyglet\gl\lib.py", line 107, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid operation'
```

**Comment by pvcraven** [comment]
What do you have for graphics hardware and drivers on the computer? Is it an older or newer computer? Arcade required OpenGL 3.3 or higher. This type of error sometimes happens with older hardware or older drivers.

**Comment by NH-VII** [comment]
I finally found the root cause issue (after  a 4 hours headache): the **RivaTuner overlay**. if it is disabled, everything runs as expected. By the way the hardware is quite new (GTX 1070 + i5 6600k) and the drivers are updated to the last version.
I hope this post can help someone else. I didn't found a similar issue searching on the net.
