### ISSUE TITLE
Arcade 2.5.2 using shapely~=1.7 which is broken on MacOS 11

### ISSUE THREAD

**Issue by richstokes** [pythonarcade/arcade#812]
## Bug Report

```
pip install arcade
Collecting arcade
  Using cached arcade-2.5.2-py3-none-any.whl (38.3 MB)
Collecting numpy==1.19.2
  Using cached numpy-1.19.2.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: pyyaml~=5.3 in /Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages (from arcade) (5.4.1)
Requirement already satisfied: pillow~=8.0 in /Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages (from arcade) (8.1.0)
Collecting shapely~=1.7
  Using cached Shapely-1.7.1.tar.gz (383 kB)
Requirement already satisfied: pytiled-parser==0.9.4a3 in /Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages (from arcade) (0.9.4a3)
Requirement already satisfied: pymunk~=5.7 in /Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages (from arcade) (5.7.0)
Requirement already satisfied: pyglet<2,>=1.5.11 in /Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages (from arcade) (1.5.14)
Requirement already satisfied: attrs in /Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages (from pytiled-parser==0.9.4a3->arcade) (20.3.0)
Requirement already satisfied: cffi!=1.13.1 in /Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages (from pymunk~=5.7->arcade) (1.14.4)
Requirement already satisfied: pycparser in /Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages (from cffi!=1.13.1->pymunk~=5.7->arcade) (2.20)
Using legacy 'setup.py install' for shapely, since package 'wheel' is not installed.
Building wheels for collected packages: numpy
  Building wheel for numpy (PEP 517) ... done
  Created wheel for numpy: filename=numpy-1.19.2-cp38-cp38-macosx_11_0_x86_64.whl size=4557792 sha256=c96cfc70b9ece86ffcca2b1c9469ae869c12d849bb4005b8be3211a02c7a2eea
  Stored in directory: /Users/rich/Library/Caches/pip/wheels/3f/19/32/44d5ff325a8aa772fde3c5742a706b9cc2712cd06e73d8d333
Successfully built numpy
Installing collected packages: numpy, shapely, arcade
  Attempting uninstall: numpy
    Found existing installation: numpy 1.18.0
    Uninstalling numpy-1.18.0:
      Successfully uninstalled numpy-1.18.0
    Running setup.py install for shapely ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/rich/.pyenv/versions/3.8.7/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/36/8b9pzfn56wd_cch3x8zx3l_w0000gn/T/pip-install-e0rq3jqa/shapely/setup.py'"'"'; __file__='"'"'/private/var/folders/36/8b9pzfn56wd_cch3x8zx3l_w0000gn/T/pip-install-e0rq3jqa/shapely/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/36/8b9pzfn56wd_cch3x8zx3l_w0000gn/T/pip-record-q22jfwjx/install-record.txt --single-version-externally-managed --compile --install-headers /Users/rich/.pyenv/versions/3.8.7/include/python3.8/shapely
         cwd: /private/var/folders/36/8b9pzfn56wd_cch3x8zx3l_w0000gn/T/pip-install-e0rq3jqa/shapely/
    Complete output (10 lines):
    init_dgelsd failed init
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/36/8b9pzfn56wd_cch3x8zx3l_w0000gn/T/pip-install-e0rq3jqa/shapely/setup.py", line 340, in <module>
        import numpy
      File "/Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages/numpy/__init__.py", line 286, in <module>
        raise RuntimeError(msg)
    RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
    RankWarning: Polyfit may be poorly conditioned

    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/rich/.pyenv/versions/3.8.7/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/36/8b9pzfn56wd_cch3x8zx3l_w0000gn/T/pip-install-e0rq3jqa/shapely/setup.py'"'"'; __file__='"'"'/private/var/folders/36/8b9pzfn56wd_cch3x8zx3l_w0000gn/T/pip-install-e0rq3jqa/shapely/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/36/8b9pzfn56wd_cch3x8zx3l_w0000gn/T/pip-record-q22jfwjx/install-record.txt --single-version-externally-managed --compile --install-headers /Users/rich/.pyenv/versions/3.8.7/include/python3.8/shapely Check the logs for full command output.
```

Looks like it might be a problem with Numpy (https://github.com/numpy/numpy/issues/15947), I tried the solutions on that page but didnt seem to help in getting python arcade to install. 

Anyone ran into this?

**Comment by pvcraven** [comment]
We hardly use numpy, I really need to get it out of there some day.

**Comment by einarf** [comment]
numpy is also an optional dependecy for shapely. I have not looked into what that means.

**Comment by einarf** [comment]
This was related to numpy. Recent versions of arcade don't have this problem. We are also removing numpy as a dependency in 2.6
