### ISSUE TITLE
arcade.Sound.stop() doesn't work

### ISSUE THREAD

**Issue by VV0JC13CH** [pythonarcade/arcade#839]
### Actual behavior:
Exception:
File "venv/lib/python3.9/site-packages/arcade/sound.py", line 72, in stop
    media.Source._players.remove(player)
ValueError: list.remove(x): x not in list
### Expected behavior:
Sound is going to stop playing
### Steps to reproduce/example code:
Launch: https://arcade.academy/examples/background_music.html#background-music and wait until end of first song :-)
### Where is it located?
arcade/sound.py
### What is wrong with it? How can it be improved?
ValueError: list.remove(x): x not in list

Trackback from background-music example:
Traceback (most recent call last):
  File "test.py", line 105, in <module>
    main()
  File "test.py", line 101, in main
    arcade.run()
  File "venv/lib/python3.9/site-packages/arcade/window_commands.py", line 240, in run
    pyglet.app.run()
  File "venv/lib/python3.9/site-packages/pyglet/app/__init__.py", line 107, in run
    event_loop.run()
  File "venv/lib/python3.9/site-packages/pyglet/app/base.py", line 167, in run
    timeout = self.idle()
  File "venv/lib/python3.9/site-packages/pyglet/app/base.py", line 237, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "venv/lib/python3.9/site-packages/pyglet/clock.py", line 292, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "venv/lib/python3.9/site-packages/arcade/application.py", line 223, in _dispatch_updates
    self.dispatch_event('on_update', delta_time)
  File "venv/lib/python3.9/site-packages/pyglet/window/__init__.py", line 1333, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "venv/lib/python3.9/site-packages/pyglet/event.py", line 415, in dispatch_event
    if getattr(self, event_type)(*args):
  File "test.py", line 94, in on_update
    self.music.stop(self.current_player)
  File "venv/lib/python3.9/site-packages/arcade/sound.py", line 72, in stop
    media.Source._players.remove(player)
ValueError: list.remove(x): x not in list

**Comment by einarf** [comment]
I'm guessing the sound was already removed by the `on_player_eos` callback. It could be a good idea to always ask if the player is in the player list before removing it? Might be a couple race conditions here?

@Cleptomania have any thoughts on this?

https://github.com/pythonarcade/arcade/blob/a0420938c7e2e1a9716cd4de1c8e2a5447f0916c/arcade/sound.py#L57-L72

**Comment by Cleptomania** [comment]
That probably is what’s happening. I think just checking if it’s in the list would be enough to prevent it from happening. We shouldn’t need to perform the check within `on_player_eos` as it could never be triggered after a stop has been. So if I just add a check in the stop functions I think we’d be good. I’ll do some testing with it tomorrow and push it to the development branch if that if that seems to work.

**Comment by einarf** [comment]
It might as well go in `maintenance` so we can push that out with a couple of other fixes

**Comment by Cleptomania** [comment]
I've pushed a fix for this to `maintenance`.

**Comment by Cleptomania** [comment]
Also found that this example hasn't been updated to work with the new sound changes either and had some other unrelated issues. I'm going to update that as well.

**Comment by einarf** [comment]
2.5.7 is released
