### ISSUE TITLE
Running tests under Windows 10 produces flood of GLExceptions

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#847]
### Actual behavior:
Attempting to run tests from project directory with `pytest` under Windows 10 spews errors such as the following, pushing the test results off screen and beyond scrollback:
```
Traceback (most recent call last):
  File "C:\Users\pushfoo\AppData\Local\Programs\Python\Python37\lib\weakref.py", line 648, in _exitfunc
    f()
  File "C:\Users\pushfoo\AppData\Local\Programs\Python\Python37\lib\weakref.py", line 572, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\pushfoo\Projects\arcade\arcade\gl\program.py", line 201, in _delete
    gl.glDetachShader(prog_id, shader_id)
  File "c:\users\pushfoo\pycharmprojects\arcade\lib\site-packages\pyglet\gl\lib.py", line 114, in errcheck
    raise GLException('(0x%x): %s' % (error, msg))
pyglet.gl.lib.GLException: (0x501): Invalid value. A numeric argument is out of range.
Traceback (most recent call last):
  File "C:\Users\pushfoo\AppData\Local\Programs\Python\Python37\lib\weakref.py", line 648, in _exitfunc
    f()
  File "C:\Users\pushfoo\AppData\Local\Programs\Python\Python37\lib\weakref.py", line 572, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\pushfoo\Projects\arcade\arcade\gl\program.py", line 201, in _delete
    gl.glDetachShader(prog_id, shader_id)
  File "c:\users\pushfoo\pycharmprojects\arcade\lib\site-packages\pyglet\gl\lib.py", line 114, in errcheck
    raise GLException('(0x%x): %s' % (error, msg))
pyglet.gl.lib.GLException: (0x501): Invalid value. A numeric argument is out of range.
Traceback (most recent call last):
  File "C:\Users\pushfoo\AppData\Local\Programs\Python\Python37\lib\weakref.py", line 648, in _exitfunc
    f()
  File "C:\Users\pushfoo\AppData\Local\Programs\Python\Python37\lib\weakref.py", line 572, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\pushfoo\Projects\arcade\arcade\gl\program.py", line 201, in _delete
    gl.glDetachShader(prog_id, shader_id)
  File "c:\users\pushfoo\pycharmprojects\arcade\lib\site-packages\pyglet\gl\lib.py", line 114, in errcheck
    raise GLException('(0x%x): %s' % (error, msg))
pyglet.gl.lib.GLException: (0x501): Invalid value. A numeric argument is out of range.
```
### Expected behavior:
Normal pytest output.

#### 1. Be on Windows 10 with this hardware:
![image](https://user-images.githubusercontent.com/36696816/114896592-7a97c780-9dde-11eb-84dc-0235dac7ff1f.png)
#### 2. Switch to development & install from source per the developer guide
```
git checkout development
pip install -e .[dev,doc]
```
#### 3. Run pytest
```
pytest
```
### Additional information
As with #845 , this is related to using pyglet 2. Forcing downgrade to `pyglet==1.5.15` results in normal pytest output returning.

**Comment by einarf** [comment]
All tests also fail on OS X currently. Need to look into that. It seems running single tests works fine possibly indicating that something goes wrong between every window creation.

Creating the window fixture globally in conftest with session scope will make two test modules pass (reusing the window and context).
```
[.venv] einarf@MacBook:arcade (development) 
$ pytest tests/unit2/test_opengl_buffer.py tests/unit2/test_opengl_texture.py 
================================================================== test session starts ===================================================================
platform darwin -- Python 3.8.6, pytest-5.4.3, py-1.8.1, pluggy-0.13.1
rootdir: /Users/einarforselv/Documents/projects/ModernGL/arcade, inifile: pytest.ini
collected 17 items                                                                                                                                       

tests/unit2/test_opengl_buffer.py ......                                                                                                           [ 35%]
tests/unit2/test_opengl_texture.py ...........
```

It's definitely related to creating a second window. I'm suspecting this is also a mac + intel thing.

**Comment by einarf** [comment]
I committed something to suppress the program/shader deletion in arcade when the context is corrupt. The true error will be more clear when pulling this change.

```
/Users/einarf/Documents/projects/arcade/.venv/lib/python3.8/site-packages/pyglet/window/__init__.py:931: in view
    with pyglet.graphics.get_default_shader().uniform_buffers['WindowBlock'] as window_block:
/Users/einarf/Documents/projects/arcade/.venv/lib/python3.8/site-packages/pyglet/graphics/shader.py:558: in __enter__
    glBindBufferBase(GL_UNIFORM_BUFFER, self.index, self.buffer.id)
```
The errors triggered by `glBindBufferBase`
```
pyglet.gl.lib.GLException: (0x502): Invalid operation. The specified operation is not allowed in the current state.
```

.. meaning there is something weird happening with the context/window.

**Comment by einarf** [comment]
Quick tests

This works perfectly
```py
import pyglet

window1 = pyglet.window.Window()
window1.close()

window2 = pyglet.window.Window()

pyglet.app.run()
```

This replicates the error we are seeing in arcade. It's related to the shadow context for some reason
```py
import pyglet
pyglet.options["shadow_window"] = False

window1 = pyglet.window.Window()
window1.close()

window2 = pyglet.window.Window()

pyglet.app.run()
```
Creating the second window creates an invalid/corrupt context when shadow window is disabled
```
  File "window_test.py", line 17, in <module>
    window2 = arcade.Window()
  File "projects/arcade/arcade/application.py", line 93, in __init__
    super().__init__(width=width, height=height, caption=title,
  File "projects/arcade/.venv/lib/python3.8/site-packages/pyglet/window/__init__.py", line 579, in __init__
    self.view = pyglet.math.Mat4()
  File "projects/arcade/.venv/lib/python3.8/site-packages/pyglet/window/__init__.py", line 931, in view
    with pyglet.graphics.get_default_shader().uniform_buffers['WindowBlock'] as window_block:
  File "projects/arcade/.venv/lib/python3.8/site-packages/pyglet/graphics/shader.py", line 558, in __enter__
    glBindBufferBase(GL_UNIFORM_BUFFER, self.index, self.buffer.id)
  File "projects/arcade/.venv/lib/python3.8/site-packages/pyglet/gl/lib.py", line 114, in errcheck
    raise GLException('(0x%x): %s' % (error, msg))
pyglet.gl.lib.GLException: (0x502): Invalid operation. The specified operation is not allowed in the current state.
```

**Comment by einarf** [comment]
https://github.com/pyglet/pyglet/issues/373

**Comment by pushfoo** [comment]
@einarf the changes pushed in [your commit](https://github.com/pythonarcade/arcade/commit/e198da4a420d5231839f00269bdaedca5cdebd91) also suppress the context errors on my system 👍

**Comment by einarf** [comment]
Fixed in latest pyglet master. There will be a new pyglet 2.0 dev releases soon
