### ISSUE TITLE
Missing font resource error 

### ISSUE THREAD

**Issue by MisoMosiSpy** [pythonarcade/arcade#906]
## Bug Report

When I build and install the arcade library with `make full` and run any examples I get following error.

```python arcade\examples\array_backed_grid.py
Traceback (most recent call last):
  File "C:\Users\dzambare\Documents\MyData\Projects\Python\arcade_build\arcade_build_env\lib\site-packages\arcade\text_pyglet.py", line 64, in load_font
    file_path = resolve_resource_path(font_name)
  File "C:\Users\dzambare\Documents\MyData\Projects\Python\arcade_build\arcade_build_env\lib\site-packages\arcade\resources\__init__.py", line 30, in resolve_resource_path
    raise FileNotFoundError(f"Cannot locate resource : {path}")
FileNotFoundError: Cannot locate resource : C:\Users\dzambare\Documents\MyData\Projects\Python\arcade_build\arcade_build_env\lib\site-packages\arcade\resources\fonts\ttf\Kenney Blocks.ttf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dzambare\Documents\MyData\Projects\Python\arcade_build\arcade_src\arcade\examples\array_backed_grid.py", line 16, in <module>
    import arcade
  File "C:\Users\dzambare\Documents\MyData\Projects\Python\arcade_build\arcade_build_env\lib\site-packages\arcade\__init__.py", line 480, in <module>
    load_font(":resources:fonts/ttf/Kenney Blocks.ttf")
  File "C:\Users\dzambare\Documents\MyData\Projects\Python\arcade_build\arcade_build_env\lib\site-packages\arcade\text_pyglet.py", line 66, in load_font
    raise FileNotFoundError(f"Unable to find resource with the name: {font_name}")
FileNotFoundError: Unable to find resource with the name: :resources:fonts/ttf/Kenney Blocks.ttf
```

Happening since commit a3395886723214e1cbacf8c6cbfba9d141d7fa41, looks like we are not copying fonts in the install package. 

Steps to reproduce:
---------------------
1. Pull latest code
2. make full
3. run any example. 

I have fixed this issue will raise the PR.

**Comment by MisoMosiSpy** [comment]
Fixed in #910
