### ISSUE TITLE
dev branch : FileNotFoundError: Unable to find resource with the name: :resources:fonts/ttf/Kenney Blocks.ttf

### ISSUE THREAD

**Issue by pyweeker** [pythonarcade/arcade#910]
hello, crash when importing arcade from pipenv with development branch

pipenv install https://github.com/pythonarcade/arcade/archive/refs/heads/development.zip

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/.local/share/virtualenvs/bugarc-ML-1O8Z8/lib/python3.8/site-packages/arcade/__init__.py", line 484, in <module>
    load_font(":resources:fonts/ttf/Kenney Blocks.ttf")
  File "/home/me/.local/share/virtualenvs/bugarc-ML-1O8Z8/lib/python3.8/site-packages/arcade/text_pyglet.py", line 67, in load_font
    raise FileNotFoundError(f"Unable to find resource with the name: {font_name}")
FileNotFoundError: Unable to find resource with the name: :resources:fonts/ttf/Kenney Blocks.ttf
```

**Comment by pvcraven** [comment]
Thanks for the report. Should be updated to work now. Please test.

**Comment by MisoMosiSpy** [comment]
This was fixed in pull request https://github.com/pythonarcade/arcade/pull/907 as well.

**Comment by pvcraven** [comment]
Closing, as it is fixed in current dev builds
