### ISSUE TITLE
Tiled template attributes not imported (.tx) 

### ISSUE THREAD

**Issue by EnlNovius** [pythonarcade/arcade#917]
## Bug Report

- On Tiled, I added on my object layer a tree, using a tree sprite. I changed the tree attribute name : name = `tree`.
If i import the object layer in python with `arcade.tilemap.get_tilemap_layer`, I have my tree object in my ObjectLayer.tiled_objects: 
`TiledObject(id_=43, gid=282, location=OrderedPair(x=71.75, y=52.75), size=Size(width=16.0, height=36.0), rotation=None, opacity=None, name='tree', type=None, properties=None, template=None)`
The object parameters in Tiled : 
![image](https://user-images.githubusercontent.com/52698559/126979640-102ab87d-7043-4736-879f-c39b81e961cb.png)
Here everything is good.

- Howether, if in Tiled I export the tree object as a Template (.tx file), and use it, when I import my object layer, I don't get the name and the size of the object :
`TiledObject(id_=39, gid=None, location=OrderedPair(x=71.75, y=51.75), size=None, rotation=None, opacity=None, name=None, type=None, properties=None, template=None)`
The template parameters in Tiled: 
![image](https://user-images.githubusercontent.com/52698559/126979545-151161db-03af-4cc7-8bb6-7c94fcc60f9d.png)

The tree.tx file : 
`<?xml version="1.0" encoding="UTF-8"?>
<template>
 <tileset firstgid="1" source="arbre.tsx"/>
 <object name="tree" gid="1" width="16" height="36"/>
</template>`

- Now, if I replace the default name declared in the template (`tree`) by another name (`tree2` for example), I get the name in python (but the size is still missing): 
`TiledObject(id_=49, gid=None, location=OrderedPair(x=295.25, y=51.25), size=None, rotation=None, opacity=None, name='tree2', type=None, properties=None, template=None)`

**Comment by pvcraven** [comment]
Is this 2.5.7 or the dev branch?

Tiled support has been redone in the dev branch, although it assumes everything is saved in JSON format. Don't know if it supports templates or not off-hand.

**Comment by EnlNovius** [comment]
Oops, I forgot to mention that. I'm on 2.5.7.
So arcade will migrate from tmx vs json? I can try with the dev branch in few hours.

**Comment by Cleptomania** [comment]
I can confirm 2.5.x does not have support for templates(or at least, not proper support). The dev branch I believe as of right now should work out of the box.

pytiled parser loads data from the templates straight into the object class now so from the Arcade it’s as if a template never existed, it’s just auto applied to the objects.

There’s a lot of other API changes for the tiled stuff in the dev branch as that whole section of Arcade is a complete re-write from 2.5.x to 2.6. We have some examples in there though.

**Comment by EnlNovius** [comment]
I just try with the latest dev version (from this afternoon), if I use object from sprite in Tiled everything work fine, but if I try to use a template I get this error (with arcade.load_tilemap) :

```
Traceback (most recent call last):
  File "/home/novius/Documents/MyProject/src/MyProject/main_center.py", line 167, in <module>
    main()
  File "/home/novius/Documents/MyProject/src/MyProject/main_center.py", line 162, in main
    window.setup()
  File "/home/novius/Documents/MyProject/src/MyProject/main_center.py", line 147, in setup
    self.decor.setup()
  File "/home/novius/Documents/MyProject/src/MyProject/main_center.py", line 51, in setup
    self.map = arcade.load_tilemap(self.map_file, scaling=SCALING)
  File "/home/novius/Documents/MyProjet/arcade/arcade/tilemap/tilemap.py", line 682, in load_tilemap
    return TileMap(map_file, scaling, layer_options)
  File "/home/novius/Documents/MyProject/arcade/arcade/tilemap/tilemap.py", line 146, in __init__
    self.tiled_map = pytiled_parser.parse_map(map_file)
  File "/home/novius/miniconda3/envs/arcade/lib/python3.8/site-packages/pytiled_parser/tiled_map.py", line 151, in parse_map
    layers=[layer.cast(layer_, parent_dir) for layer_ in raw_tiled_map["layers"]],
  File "/home/novius/miniconda3/envs/arcade/lib/python3.8/site-packages/pytiled_parser/tiled_map.py", line 151, in <listcomp>
    layers=[layer.cast(layer_, parent_dir) for layer_ in raw_tiled_map["layers"]],
  File "/home/novius/miniconda3/envs/arcade/lib/python3.8/site-packages/pytiled_parser/layer.py", line 501, in cast
    return caster(raw_layer, parent_dir)
  File "/home/novius/miniconda3/envs/arcade/lib/python3.8/site-packages/pytiled_parser/layer.py", line 418, in _cast_object_layer
    tiled_objects.append(tiled_object.cast(tiled_object_, parent_dir))
  File "/home/novius/miniconda3/envs/arcade/lib/python3.8/site-packages/pytiled_parser/tiled_object.py", line 413, in cast
    loaded_template = json.load(raw_template_file)["object"]
  File "/home/novius/miniconda3/envs/arcade/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/novius/miniconda3/envs/arcade/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/novius/miniconda3/envs/arcade/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/novius/miniconda3/envs/arcade/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1
```

I will try to prepare a simple example that reproduces the error (hoping it's not a mistake on my part).

**Comment by pvcraven** [comment]
Take a look at the file you are opening in the text editor. Make sure it is JSON formatted.

**Comment by EnlNovius** [comment]
I checked the file and it is a json (it worked without the template in the object layer).

**Comment by EnlNovius** [comment]
Ok I found the problem: the .tx format is also to be replaced by .json.
Thank you for your help.
