### ISSUE TITLE
FileNotFoundError: Cannot locate resource : Pac-man.png

### ISSUE THREAD

**Issue by alderven** [pythonarcade/arcade#967]
Run code from this example: https://api.arcade.academy/en/latest/tutorials/crt_filter/index.html

Getting error:
```
Traceback (most recent call last):
  File "C:/arcade_lib/crt_filter.py", line 105, in <module>
    MyGame(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)
  File "C:/arcade_lib/crt_filter.py", line 31, in __init__
    full = arcade.Sprite(RESOURCE_DIR / "Pac-man.png")
  File "C:\Program Files\Python38\lib\site-packages\arcade\sprite.py", line 247, in __init__
    self._texture = load_texture(
  File "C:\Program Files\Python38\lib\site-packages\arcade\texture.py", line 438, in load_texture
    file_name = resolve_resource_path(file_name)
  File "C:\Program Files\Python38\lib\site-packages\arcade\resources\__init__.py", line 30, in resolve_resource_path
    raise FileNotFoundError(f"Cannot locate resource : {path}")
FileNotFoundError: Cannot locate resource : C:\arcade_lib\Pac-man.png
```

**Comment by einarf** [comment]
I guess it might not be clear in the docs that the resources are in the doc strucutre: https://github.com/pythonarcade/arcade/tree/development/doc/tutorials/crt_filter

**Comment by alderven** [comment]
It would be more convenient to define resources in script in following format: `arcade.Sprite(":resources:image.png")`

**Comment by pvcraven** [comment]
Added some additional explanation on where to find the images. Don't think I'll move this to resources though.
