### ISSUE TITLE
arcade.Text appears to be broken in multiple ways

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#992]
### Actual behavior:
Attempting to use arcade.Text fails at the constructor. This can be suppressed by using `get_four_bye_color`, but the implementation appears to still be broken. For example: Attempting to draw a circle to check where the text is drawing produces additional issues.

### Expected behavior:
arcade.Text initializes and draws without crashing when other things are drawn.

### Steps to reproduce/example code:
Run the code below off the tip of develop:
```py
import arcade
from arcade import Text

class TextObjectExample(arcade.Window):
    def __init__(self, width, height, title):
        super().__init__(width, height, title)

        self.text = Text(
            "should draw",
            self.width / 2, self.height / 2
        )

    def on_draw(self):
        arcade.start_render()
        self.text.draw()

if __name__ == "__main__":
    window = TextObjectExample(640, 480, "Text")
    arcade.run()
 ```
 and get this output, which can be suppressed by using `get_four_byte_color` inside the constructor of `Text`:
 ```
 Traceback (most recent call last):
  File "C:/Users/user/Projects/arcade/text_object.py", line 26, in <module>
    window = TextObjectExample(640, 480, "Text")
  File "C:/Users/user/Projects/arcade/text_object.py", line 12, in __init__
    color=arcade.color.WHITE
  File "C:\Users\user\Projects\arcade\arcade\text_pyglet.py", line 45, in __init__
    italic=italic,
  File "C:\Users\user\PycharmProjects\arcade\lib\site-packages\pyglet\text\__init__.py", line 478, in __init__
    'align': align,
  File "C:\Users\user\PycharmProjects\arcade\lib\site-packages\pyglet\text\document.py", line 597, in set_style
    0, len(self.text), attributes)
  File "C:\Users\user\PycharmProjects\arcade\lib\site-packages\pyglet\text\document.py", line 505, in set_style
    self.dispatch_event('on_style_text', start, end, attributes)
  File "C:\Users\user\PycharmProjects\arcade\lib\site-packages\pyglet\event.py", line 415, in dispatch_event
    if handler(*args):
  File "C:\Users\user\PycharmProjects\arcade\lib\site-packages\pyglet\text\layout.py", line 1396, in on_style_text
    self._init_document()
  File "C:\Users\user\PycharmProjects\arcade\lib\site-packages\pyglet\text\layout.py", line 1360, in _init_document
    self._update()
  File "C:\Users\user\PycharmProjects\arcade\lib\site-packages\pyglet\text\layout.py", line 1284, in _update
    self._create_vertex_lists(left + line.x, top + line.y, line.start, line.boxes, context)
  File "C:\Users\user\PycharmProjects\arcade\lib\site-packages\pyglet\text\layout.py", line 1763, in _create_vertex_lists
    box.place(self, i, x, y, context)
  File "C:\Users\user\PycharmProjects\arcade\lib\site-packages\pyglet\text\layout.py", line 371, in place
    'translation2f/dynamic')
  File "C:\Users\user\PycharmProjects\arcade\lib\site-packages\pyglet\graphics\__init__.py", line 451, in add_indexed
    vlist.set_attribute_data(i, array)
  File "C:\Users\user\PycharmProjects\arcade\lib\site-packages\pyglet\graphics\vertexdomain.py", line 385, in set_attribute_data
    region.array[:] = data
ValueError: Can only assign sequence of same size
```

However, there are still problems. The text does not draw, and attempting to draw another shape causes the program to crash. Running the code below with the draw call on self.text commented out works fine and draws the circle:
```py
import arcade
from arcade import Text


class TextObjectWithCircle(arcade.Window):
    def __init__(self, width, height, title):
        super().__init__(width, height, title)

        self.text = Text(
            "should draw",
            self.width / 2, self.height / 2,
            color=arcade.color.WHITE
        )

    def on_draw(self):
        arcade.start_render()

        self.text.draw()
        arcade.draw_circle_filled(
            self.width / 2, self.height / 2,
            radius=3,
            color=(255,0,0, 255)
        )

if __name__ == "__main__":
    window = TextObjectWithCircle(640, 480, "Text")
    arcade.run()
```
Running it with the text draw call gets this result:
```
Traceback (most recent call last):
  File "C:/Users/user/Projects/arcade/text_object.py", line 27, in <module>
    arcade.run()
  File "C:\Users\user\Projects\arcade\arcade\window_commands.py", line 269, in run
    pyglet.app.run()
  File "C:\Users\user\PycharmProjects\arcade\lib\site-packages\pyglet\app\__init__.py", line 107, in run
    event_loop.run(interval)
  File "C:\Users\user\PycharmProjects\arcade\lib\site-packages\pyglet\app\base.py", line 183, in run
    timeout = self.idle()
  File "C:\Users\user\PycharmProjects\arcade\lib\site-packages\pyglet\app\base.py", line 244, in idle
    self.clock.call_scheduled_functions(dt)
  File "C:\Users\user\PycharmProjects\arcade\lib\site-packages\pyglet\clock.py", line 274, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "C:\Users\user\PycharmProjects\arcade\lib\site-packages\pyglet\app\base.py", line 154, in _redraw_windows
    window.dispatch_event('on_draw')
  File "C:\Users\user\PycharmProjects\arcade\lib\site-packages\pyglet\window\__init__.py", line 1327, in dispatch_event
    super().dispatch_event(*args)
  File "C:\Users\user\PycharmProjects\arcade\lib\site-packages\pyglet\event.py", line 422, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:/Users/user/Projects/arcade/text_object.py", line 22, in on_draw
    color=arcade.color.RED
  File "C:\Users\user\Projects\arcade\arcade\draw_commands.py", line 224, in draw_circle_filled
    num_segments=num_segments)
  File "C:\Users\user\Projects\arcade\arcade\draw_commands.py", line 294, in draw_ellipse_filled
    program['color'] = color_normalized
  File "C:\Users\user\Projects\arcade\arcade\gl\program.py", line 238, in __setitem__
    uniform.setter(value)
  File "C:\Users\user\Projects\arcade\arcade\gl\uniform.py", line 184, in setter_func
    gl_setter(location, array_length, ptr)
  File "C:\Users\user\PycharmProjects\arcade\lib\site-packages\pyglet\gl\lib.py", line 114, in errcheck
    raise GLException('(0x%x): %s' % (error, msg))
pyglet.gl.lib.GLException: (0x502): Invalid operation. The specified operation is not allowed in the current state.
```

**Comment by pushfoo** [comment]
There are two core causes to this issue:
1. `get_four_byte_color` isn't called to ensure a color `pyglet.text.Label` accepts gets passed to its constructor. 
2. `with window.ctx.pyglet_rendering():` needs to be used before pyglet's label's draw function is called to set up correct GL state.

Those are an easy fix, but I'll also make some more changes to ensure that font loading works the same way for both `arcade.Text` objects and `arcade.draw_text`.

Extending the current implementation of `Text` with more properties for `color` and other things is beyond the scope of this ticket so I'll save that for later.
